### ISSUE TITLE
DB deadlock issue

### ISSUE THREAD

**Issue by awestbha** [veda-consulting/uk.co.vedaconsulting.mailchimp#102]
We had this working for a while, but it now dies with a DB:unknown error. The log says:

ERROR DEBUGINFO: 
UPDATE civicrm_group g
SET    g.refresh_date = 20141117162050
WHERE  g.id IN ( 557,558 )
AND    g.refresh_date IS NULL
 [nativecode=1213 ** Deadlock found when trying to get lock; try restarting transaction]

Has anyone come across this one?

**Comment by veda-consulting** [comment]
@awestbha closing for now, its more core issue then a mailchimp sync one.
