### ISSUE TITLE
New "DB Error: constraint violation"

### ISSUE THREAD

**Issue by jtbayly** [veda-consulting/uk.co.vedaconsulting.mailchimp#108]
I'm getting an error when trying to sync from CiviCRM to Mailchimp. Here is the text that is shown:

    [Error: List 1 all-mailchimp group: Fetched data from Mailchimp]
    DB Error: constraint violation

I looked in the log and found that it says the following: 

    [info] $CRM_Queue_Page_AJAX_runNext_error = PEAR_Exception: "DB Error: constraint violation"

Then later on I have this at the end of a line of 

    [nativecode=1048 ** Column 'email' cannot be null]

**Comment by veda-consulting** [comment]
@jtbayly I'll close for now, re-open if you get to the bottom of it. Not had reports from anyone else on this.

**Comment by jtbayly** [comment]
I don't know what's going on. I am running 1.6 and here is what the debug says:

INSERT INTO tmp_mailchimp_push_m VALUES(NULL, NULL, NULL, NULL, NULL, '40cd750bba9870f18aada2478b24840a', 'a:0:{}') [nativecode=1048 ** Column 'email' cannot be null]

Any suggestion of how I can figure out what contact is causing that? Is that long hex number a checksum that I can decode? I'm happy to spend some time on this, but I've got no idea how to take it further. This is a group of 3000 contacts, so it's not like I can just look through them.

Thanks,
