### ISSUE TITLE
sync info missing on "manage groups" page

### ISSUE THREAD

**Issue by jtbayly** [veda-consulting/uk.co.vedaconsulting.mailchimp#109]
I just updated to CiviCRM 4.5.4 from 4.4.x. Before, when I visited the "Manage Groups" page, it would show two columns describing the sync relationship between the groups and Mailchimp. Now that info is missing. 

I'm guessing this was not an intentional change, because I'm using the same version of the extension (1.5).

I'm also wondering if this bug is causing the odd sizing of the table that I'm now seeing on that same page.

Thanks again for an awesome extension.
-Joseph

**Comment by veda-consulting** [comment]
@jtbayly make sure your running the latest version of the extension. We haven't seen this issue ourselves, we have the extension running on at least a dozen 4.5 sites so not sure why yours would differ?

**Comment by veda-consulting** [comment]
@jtbayly we're closing this, we're up to 1.7 on the extension. Please raise a new issue if it happens again.
