### ISSUE TITLE
Secondary emails in Civi are removed from Mailchimp list when sync occurs

### ISSUE THREAD

**Issue by jason-vivid** [veda-consulting/uk.co.vedaconsulting.mailchimp#114]
We have multiple email addresses for individuals in our database.  Basically home and work emails.  

If I understand our current issue correctly the Mailchimp extension only syncs up the primary record.   If that individual has both emails in Mailchimp or adds a second one, the webhook pushes it to Civi, finds that it is already in the non-primary spot and doesn't do anything.  However, the next time the CiviCRM sync fires, it unsubscribes the 2nd email address from Mailchimp because it is a non-primary record.  

Other than splitting the record and creating two primary contact records (one for each email) is there a workaround for this or can we see the 2nd emails not being unsubscribed?

**Comment by veda-consulting** [comment]
@jason-vivid not that we can think of. I think this is an enhancement to the process and we'd need some guidance as to how the expected behaviour might be?

**Comment by jason-vivid** [comment]
FYI for others, our org setup those secondary emails as separate contact records and created a relationship.  This way both are kept as primary records and can be synced with MC.

@veda-consulting Yes this would be an enhancement.  I think a simple solution would be that before the MC extension sync performs an unsubscribe it checks to see if that email address is in a location other than the primary record.  If in fact it is, the sync should not perform an unsubscribe.

**Comment by veda-consulting** [comment]
@jason-vivid we've added some checks for this in the latest version, please test and feedback.
