### ISSUE TITLE
What causes list/batch unsubscribe

### ISSUE THREAD

**Issue by amorphous** [veda-consulting/uk.co.vedaconsulting.mailchimp#116]
We've had an issue with a client that has had a list/batch-unsubscribe call that was made from the API key labeled "CiviCRM - Ad Hoc Monitors" (mailchimps words).

Does this happen if multiple users are removed from a group? Do you know what workflow could have sent the request?

Apologies for not having much info atm, but a general idea may be really helpful.

Thanks,
M.

**Comment by veda-consulting** [comment]
@amorphous the sync process calls batch unsubscribe where there are contacts in mailchimp group but not in CiviCRM. There was a setting change in 1.6 to stop the batch update actually doing a delete in Mailchimp so our advice would be to upgrade to 1.6 and also your first action should be a pull from Mailchimp to CiviCRM as this will avoid lists being emptied in error.

**Comment by amorphous** [comment]
Thanks @veda-consulting

**Comment by amorphous** [comment]
@veda-consulting is: *Call Mailchimp.SyncSmartGroups API" the correct job to call for batch-unsubscribe?

**Comment by marsh-circle** [comment]
Hi @veda-consulting,
Could you respond to the above question (or is it a silly question - sorry, I'm playing middle-man :/ )
