### ISSUE TITLE
Bounce processing

### ISSUE THREAD

**Issue by jtbayly** [veda-consulting/uk.co.vedaconsulting.mailchimp#117]
When an email sent by mailchimp bounces, the contact is "cleaned." I think it would be ideal if that email address in CiviCRM were marked as "on hold."

Thanks,
-Joseph

**Comment by jason-vivid** [comment]
2nd this request.

**Comment by shawnholt** [comment]
This is how civicrm and other integrations handle bounce processing.

**Comment by vajeevan** [comment]
This issue has been fixed in mailchimp extension Version 1.8. Please have a look.

**Comment by veda-consulting** [comment]
@jason-vivid closing, please re-open if its still an issue.
