### ISSUE TITLE
Mailchimp menu glitch

### ISSUE THREAD

**Issue by magnolia61** [veda-consulting/uk.co.vedaconsulting.mailchimp#120]
Hello,
Iḿ using the module with civicrm 4.5.5 and drupal 7.3.4
See the screenshot below to notice the mailchimp menu is misplaced.
Is this caused by version compatibility or something else?

![image](https://cloud.githubusercontent.com/assets/2195908/5794463/83f0c608-9f6e-11e4-861d-fd17873ec24d.png)

**Comment by veda-consulting** [comment]
Hi, Its not a version issue. It may be down to the fact that you have some custom menus but this hasn't been reported before. We'd need to try it out.

**Comment by veda-consulting** [comment]
@magnolia61 closing, not had any feedback for a while and likely not a macilhimp extension issue.
