### ISSUE TITLE
Parent Group unsubscribe via webhook leaves child-groups intact in Civi

### ISSUE THREAD

**Issue by jason-vivid** [veda-consulting/uk.co.vedaconsulting.mailchimp#121]
We've found that when a user unsubscribes from a list via a campaign, the webhook fires and removes the main civi (parent) group, but the civi regular (child) groups which equate to the MC interest groups are still left in the contact's record.

In MC they are obviously removed, but civi does not reflect that.  See screenshot.

![image](https://cloud.githubusercontent.com/assets/10146532/5844039/e47f7f52-a17e-11e4-88df-8ccb0f765a21.png)

**Comment by veda-consulting** [comment]
@jason-vivid so in Mailchimp does unsubscribing from the parent group also unsubcribe from all child groups? Or are we talking about slightly different processes?

**Comment by jason-vivid** [comment]
@veda-consulting 

Unsubscribing in Mailchimp removes the entire contact from your list (which is an email address) and prevents you from sending mail to those interest groups.  Technically if you view the contact in MC's unsubscribed list the interest groups are still there.  However since the contact has unsubscribed they are saying they no longer want to receive mail at that particular email address.  In my mind this means that when they unsubscribe from the MC list (parent group in Civi terminology) it should also take them out of all the associated interest groups in Civi (which are child groups).  In the Civi MC extension (screenshot attached) this is marked with a * and called a Mailchimp Group.  

This is different than when a user updates their preferences in MC which allows them to select/deselect interest groups (MC terminology).  

In the attached screenshot that's an equals sign between the two lists showing that the Mailchimp list is the parent group within civi.  

![image](https://cloud.githubusercontent.com/assets/10146532/5861983/229f1f1e-a23c-11e4-8f7d-13b245ccb6de.png)

**Comment by veda-consulting** [comment]
@jason-vivid ok thanks for the overview. So I think the action should be to remove the contact from any of the groups in CiviCRM that are associated with the Mailchimp list they unsubscribed from, do you agree?

**Comment by jtbayly** [comment]
I can't pretend to understand how this is "supposed to work," but I can tell you that what is described here would not work for us, assuming I'm not misunderstanding what is proposed.

We currently have groups like "Attended an event" and "donated." We make a smart group consisting of people who are in those other groups. We use that smart group as the master list for Mailchimp. We also sync the sub-groups as interest groups (hidden from the user) so that we can send emails to particular sub-groups of people. As far as I can tell (again, correct me if I'm wrong), currently if somebody unsubscribes, they are removed from the "master list" smart group in CiviCRM, but left in the sub-groups, which is exactly what we want. We don't want them removed from the "donated" list just because they unsubscribed. Obviously in Mailchimp they won't show up in those subgroups anymore, but they do in CiviCRM.

**Comment by jason-vivid** [comment]
@veda-consulting Yes.  If they unsubscribed from a MC list, Civi should not retain any interest groups <ul>that are linked</ul>.  Different civi setups may have the interest groups as a child, or on it's own.  But either way if they unsubscribe in MC all of the connected interest groups should be pulled.  The MC extension says this, "Sync membership of with a Mailchimp interest grouping."  It is any of these ones that should be pulled.    If the MC list gets taken out, whether or not the interest groups are children or not of a civi parent group they should be removed.  All of our interest groups are setup as children to the list at the moment so I can't test if they are stand-alone (parent without children), what would happen but in either case the list should take out the MC connected interest groups with it.

@jtbayly From the situation you described you need to have two separate groups, ones that are linked to the interest groups, and ones that are not if you desire to retain the information you are looking for (ie donated, attended an event, etc..)  You want to keep that important information on hand in Civi, even if they remove themselves from the MC list, which means you need a non-connected (to the interest group) smart group.  In your case because they are hidden interest groups this probably hasn't been an issue. We have public interest groups so it does and that means when users update their MC profile, the interest groups are updated in civi as well.  There are several ways that you can setup Civi to retain contacts/information on a group but the key is that you can't have it connected to the MC interest group.    Otherwise like you have pointed out you will lose the contacts in the group.

**Comment by jason-vivid** [comment]
Any movement on this?  My earlier answer to @veda-consulting question (4th post on the thread) was yes.  

Right now I'm having a team member go in and unsubscribe all the equivalent interest groups in Civi when a person unsubscribes in MC from a list.  Although it doesn't affect the mailers they receive (no longer) via Mailchimp, CiviCRM still reflects that they are part of the interest groups.

**Comment by veda-consulting** [comment]
@jason-vivid I think we've addressed this in the latest version but please test and confirm.

**Comment by jason-vivid** [comment]
This fix did not work.
