### ISSUE TITLE
Getting an error DB Error: no database selected

### ISSUE THREAD

**Issue by vishram74** [veda-consulting/uk.co.vedaconsulting.mailchimp#122]
I am trying to sync from CiviCRM to Mailchimp but keep getting the error for one particular list
DB Error: no database selected

Please help!

**Comment by vishram74** [comment]
This is the exact error for my list called Community News
[Error: List 1 Community News: Fetched data from CiviCRM]
DB Error: no database selected

**Comment by vishram74** [comment]
Further to this, I am syncing another 2 lists and there are no issues with these.
The list with an error has <11k contacts in Civi.  Could this be the issue? 
The other lists have <6k contacts

**Comment by erogers** [comment]
I also have this error on all lists where I am trying to sync to interest groups, not the parent list. 

Civi 4.6.2, WP 4.2, Extension 1.7

**Comment by Kajakaran** [comment]
Hi @erogers ,

I could not reproduce this error. However I wonder if you have done set up correctly civicrm groups with Malichimp interesting group

This is how I have configured and tested.

CiviCRM Groups    ||| Mailchimp List    |||Mailchimp Interesting Grouping   ||  Mailchimp Intersting group

Advisory Board (Parent)(option 2------>TueList

Summer Program Volunteers (Child)(option 3-->TueList -> Intersting Groups -> Intersting group1

Civi 4.6.2 WP 4.2.2 Extension 1.7

Thanks
Kajan

**Comment by veda-consulting** [comment]
@erogers closing as not heard anything back. Please report a new issue if your still having issues.
