### ISSUE TITLE
Ref:  What causes list/batch unsubscribe #116 

### ISSUE THREAD

**Issue by phil-circle** [veda-consulting/uk.co.vedaconsulting.mailchimp#123]
Hi Guys, in the above referenced issue you say:

the sync process calls batch unsubscribe where there are contacts in mailchimp group but not in CiviCRM. There was a setting change in 1.6 to stop the batch update actually doing a delete in Mailchimp so our advice would be to upgrade to 1.6 and also your first action should be a pull from Mailchimp to CiviCRM as this will avoid lists being emptied in error.

Can I ask the name of the pull job (just before I do something stupid)?

It's been asked there but not sure if you'd have seen it.

Thanks

**Comment by veda-consulting** [comment]
Hi @phil-circle I would suggest upgrading to the latest version (v1.7) due to come out tomorrow. This combines the sync job into a single pull and push. I would still suggest you export your mail chimp lists before running this for the first time.
