### ISSUE TITLE
4.6 readyness

### ISSUE THREAD

**Issue by magnolia61** [veda-consulting/uk.co.vedaconsulting.mailchimp#126]
With the 4.6 in beta since today i was wondering, do you foresee any issues with compatibility (or would you think this extension will have no big issues working in 4.6? Of course I will also try and test myself, but you know the architecture of the extension and changes in civicrm better than I do :-)

**Comment by veda-consulting** [comment]
We'll try it out soon and feedback but we don't imagine any major changes. 4.6 changes are fairly well contained away from the integration.
