### ISSUE TITLE
"DB Error: no such table" when installing in Wordpress 4.1.1 / CivicCRM 4.4

### ISSUE THREAD

**Issue by joesalowitz** [veda-consulting/uk.co.vedaconsulting.mailchimp#127]
I received a DB Error when trying to install via the Wordpress interface. I can replicate this every time I try to install. Any ideas?

**Comment by veda-consulting** [comment]
@joesalowitz we can't reproduce this, could you confirm the exact steps your taking?

**Comment by veda-consulting** [comment]
@joesalowitz we're closing as not heard anything back
