### ISSUE TITLE
Webhook permissions in Joomla?

### ISSUE THREAD

**Issue by norristh** [veda-consulting/uk.co.vedaconsulting.mailchimp#128]
When I installed the latest version, 1.6, with CiviCRM 4.5.6, under Joomla, it gave an error about not being able to create permissions: "Some modules define permissions, but the CMS cannot store them: mailchimp"

I can use the extension to sync manually from mailchimp, but I can't get webhooks to work.  I believe the configuration screen gives the wrong address.  It says to use http://MYSITE.COM/index.php?option=com_civicrm&task=civicrm/mailchimp/webhook&reset=1&key=MYKEY but that goes to a Joomla error screen. 

http://MYSITE.COM/administrator/index.php?option=com_civicrm&task=civicrm/mailchimp/webhook&reset=1&key=MYKEY  works (prints "null"), but only when I'm already authenticated (logged in) to joomla.  Otherwise it redirects to a login screen.  Of course this doesn't work as the webhook URL within mailchimp.

How do I set up public access to that administrator/index.php?option=com_civicrm&task=civicrm/mailchimp/webhook area?

**Comment by TheOnePom** [comment]
I have exactly the same issue.

**Comment by vajeevan** [comment]
This issue has been fixed in mailchimp extension Version 1.8. Please have a look.

**Comment by TheOnePom** [comment]
Thanks Vajeevan, where would I find 1.8?

**Comment by veda-consulting** [comment]
@TheOnePom 1.8 is in the extensions directory, we've just released 1.8.1 with a minor bug fix. Closing the issue, please re-open if its not fixed.
