### ISSUE TITLE
syncing deleted contacts

### ISSUE THREAD

**Issue by joseltorres** [veda-consulting/uk.co.vedaconsulting.mailchimp#130]
It seems if a contact has been deleted (trashed) but not deleted permanently it will still sync with the mailchimp list.

**Comment by joseltorres** [comment]
...additionally, I noticed that if the contact record does not exist, but records in the **civicrm_email** and **civicrm_group_contact** tables record exist, the email still gets synced to mailchimp.  

-i know this is probably a data issue in this civi db, but I think this could be solved by checking the "deleted" value for the contact.

**Comment by veda-consulting** [comment]
@joseltorres ok, we can see this. We'll patch  fix in our next release.

**Comment by vajeevan** [comment]
This issue has been fixed in mailchimp extension Version 1.8. Please have a look.

**Comment by joseltorres** [comment]
Good news. I will check it soon. Thanks.

**Comment by veda-consulting** [comment]
@joseltorres closing, please reopen if its still an issue.
