### ISSUE TITLE
MailChimp CiviCRM Sync NOT WORKING

### ISSUE THREAD

**Issue by RicaWWCC** [veda-consulting/uk.co.vedaconsulting.mailchimp#131]
Hello, Our MailChimp and CiviCRM sync is not working. I receive the following error message: 
"Sorry but we are not able to provide this at the moment.
DB Error: no such field"

Our developer looked into this and could not figure out the error. I have not coding background, but am looking for a solution or guidance on what to do. Any help would be appreciated. 

Thank you.

Here is the entire error message I received from the developer:
Database Error Code: Unknown column 'is_mc_update_grouping' in 'field list', 1054
Additional Details:
 
Array
(
    [callback] => Array
        (
            [0] => CRM_Core_Error
            [1] => handle
        )
    [code] => -19
    [message] => DB Error: no such field
    [mode] => 16
    [debug_info] => 
      SELECT  entity_id, mc_list_id, mc_grouping_id, mc_group_id, is_mc_update_grouping, cg.title as civigroup_title, cg.saved_search_id, cg.children
 FROM    civicrm_value_mailchimp_settings mcs
      INNER JOIN civicrm_group cg ON mcs.entity_id = cg.id
      WHERE mc_list_id IS NOT NULL AND mc_list_id <> '' AND (mc_grouping_id IS NULL OR mc_grouping_id = '') [nativecode=1054 ** Unknown column 'is_mc_update_grouping' in 'field list']
    [type] => DB_Error
    [user_info] => 
      SELECT  entity_id, mc_list_id, mc_grouping_id, mc_group_id, is_mc_update_grouping, cg.title as civigroup_title, cg.saved_search_id, cg.children
 FROM    civicrm_value_mailchimp_settings mcs
      INNER JOIN civicrm_group cg ON mcs.entity_id = cg.id
      WHERE mc_list_id IS NOT NULL AND mc_list_id <> '' AND (mc_grouping_id IS NULL OR mc_grouping_id = '') [nativecode=1054 ** Unknown column 'is_mc_update_grouping' in 'field list']
    [to_string] => [db_error: message="DB Error: no such field" code=-19 mode=callback callback=CRM_Core_Error::handle prefix="" info="
      SELECT  entity_id, mc_list_id, mc_grouping_id, mc_group_id, is_mc_update_grouping, cg.title as civigroup_title, cg.saved_search_id, cg.children
 FROM    civicrm_value_mailchimp_settings mcs
      INNER JOIN civicrm_group cg ON mcs.entity_id = cg.id
      WHERE mc_list_id IS NOT NULL AND mc_list_id <> '' AND (mc_grouping_id IS NULL OR mc_grouping_id = '') [nativecode=1054 ** Unknown column 'is_mc_update_grouping' in 'field list']"]
)

**Comment by veda-consulting** [comment]
Hi @RicaWWCC could you provide some background to this please? Did you upgrade to the latest version? Was it working before? Thanks

**Comment by RicaWWCC** [comment]
Hi, it was working before yes. As far as I know it is the most updated version.

**Comment by veda-consulting** [comment]
@RicaWWCC ok thanks, can you confirm your version of CiviCRM and which CMS (Including version) your on please.

**Comment by RicaWWCC** [comment]
CiviCRM 4.4.4.

Drupal 6.30

**Comment by RicaWWCC** [comment]
Hi,

Thank you for your email.

We are using

CiviCRM 4.4.4.

Drupal 6.30

Best Regards,

Erica

Erica Heisdorf Bisquerra
Neighborhood Education & Outreach Coordinator
Walnut Way Conservation Corp.<http://www.walnutway.org/>
2240 North 17th Street | Milwaukee, WI 53205
414.264.2326 | 414.265.7245 Fax
Newsletter<http://walnutway.us6.list-manage.com/subscribe/post?u=bf833b5026fad67d7800da9fa&id=a6e7415a50>  | Facebook<https://www.facebook.com/walnut.way?fref=ts>  | Vimeo<http://vimeo.com/walnutway>
Walnutway.org<http://walnutway.org/> | Twitter<https://twitter.com/walnut_way> | Youtube<http://www.youtube.com/user/WalnutWay?feature=watch>

[http://nicholasswenor.com/WWay/WalnutWayLogo.gif]

[Logo]<http://www.walnutway.org/donate>

This message (including any attachments) is intended only for the use of the individual or entity to which it is addressed and may contain information that is non-public, proprietary, privileged, confidential, and exempt from disclosure under applicable law or may constitute as attorney work product. If you are not the intended recipient, you are hereby notified that any use, dissemination, distribution, or copying of this communication is strictly prohibited. If you have received this communication in error, notify us immediately by telephone and (i) destroy this message if a facsimile or (ii) delete this message immediately if this is an electronic communication. Thank you

**Comment by veda-consulting** [comment]
Hi @RicaWWCC 

Looks like the upgrade of the extension wasn't clean so to speak.

Could you get your developer to run this command into the DB and try the extension again?

Alter table civicrm_value_mailchimp_settings add column is_mc_update_grouping BOOLEAN  DEFAULT NULL COMMENT 'Are subscribers able to update this grouping using mail chimp?';

Thanks

**Comment by RicaWWCC** [comment]
Hello, that command did the trick! Thank you so much!
