### ISSUE TITLE
Invalid MailChimp List : issue when syncing contacts between Civi and Mailchimp 

### ISSUE THREAD

**Issue by ERELOSInfo** [veda-consulting/uk.co.vedaconsulting.mailchimp#132]
Hello,

I'm reopening an issue when syncing (with v1.7 and previous) contacts between Civi and Mailchimp - screenshot below :

![98ceb4f0-c9a2-11e4-95a8-4af4ba256c5d 1](https://cloud.githubusercontent.com/assets/11462701/6864916/2c9869cc-d468-11e4-9abf-d6c870500efa.png)

When accessing the Mailchimp Export API from my browser with this url : https://[yourdatacentre].api.mailchimp.com/export/1.0/list?apikey=[apikey]&id=[listid]. 

i got the following result whatever the list id chosen (I've 4 of them) : {"error":"Invalid MailChimp List ID: 53089","code":200}

My DC is "us10".

Enclosed is the log provided by the Mailchimp console. Issue when trying with the CiviSync module seems different code : (211) List_InvalidOption

![a9850ec4-cd9f-11e4-996c-8afcf71c3dac 1](https://cloud.githubusercontent.com/assets/11462701/6864905/fcf5525c-d467-11e4-9c8a-9c5c7561181a.png)

Does this affect the sync cron job between Civi and Mailchimp ?
Could you please advise ?

**Comment by ERELOSInfo** [comment]
I created one group within each list and the 211 error disappear from MailChimp API calls report. But I still get an error using the Sync module in CiviCRM : 

![image](https://cloud.githubusercontent.com/assets/11462701/6880894/1fde7e54-d546-11e4-84c3-c5ddbab6c0c3.png)

**Comment by ERELOSInfo** [comment]
Hello, 
Could you please get back to me on this topic, this is still happening (after migrating to 1.8.5) ?
Thanks

**Comment by ERELOSInfo** [comment]
Hello could you please advise, extension is not adding new contacts to Mailchimp lists from CiviCRM new contacts. Thanks

**Comment by deepak-srivastava** [comment]
@ERELOS We have re-opened and replied to https://github.com/veda-consulting/uk.co.vedaconsulting.mailchimp/issues/129. Lets continue the discussion there. Closing this one for being duplicate.
