### ISSUE TITLE
Middle name & last name mixup

### ISSUE THREAD

**Issue by magnolia61** [veda-consulting/uk.co.vedaconsulting.mailchimp#133]
In the Netherlands we tend to use the Middle Name field for cases like: Joe van Vliet (van would be middle name). This is how we set up mailchimp.

Now when syncing from mailchimp to civicrm, the last name field was filled with the middle name.
In Mailchimp they are named FNAME, MNAME, LNAME.

Is there a possibility the wrong fields got synced? Our civicrm database is a mess now, since people now have their Middle Name duplicated in the Last Name field.

**Comment by veda-consulting** [comment]
@magnolia61 at present the integration does not deal with anything but the first and last name, we could look at this as an enhancement.

**Comment by deepak-srivastava** [comment]
We no longer able to reproduce this with latest v2.x release. Closing it. Please re-open if the issue still exist. Thanks.
