### ISSUE TITLE
Sync ignores CiviCRM Dedupe rules 

### ISSUE THREAD

**Issue by magnolia61** [veda-consulting/uk.co.vedaconsulting.mailchimp#134]
As briefly mentioned in https://github.com/veda-consulting/uk.co.vedaconsulting.mailchimp/issues/133 when syncing from mailchimp the extension ignored the configured dedupe rules which possibly leads to duplicates and wronlgy overwritten records.

In our civicrm situation email adres is not a unique field. We organise summer camps, and the records of the children have their parents email to it. Therefor we have a civicrm unsupervised dedupe rule for:
First Name / Last Name / Email. But this rule is ignored during sync.

Would it be possible to have this extention to follow the unsupervised rule when syncing? Right now we cannot do a pull, as it messes up all records that share the same primary email.

**Comment by veda-consulting** [comment]
@magnolia61 for the current version this is the functionality. We're going to be putting together a poll for the next set of features to be added to the extension so please keep an eye out for that.

**Comment by deepak-srivastava** [comment]
We think latest v2.x has fixed this. Please re-open if the issue still exist. Thanks.
