### ISSUE TITLE
Can only be member of one group in mail chimp when subscribed to multiple groups in CiviCRM

### ISSUE THREAD

**Issue by trackleft** [veda-consulting/uk.co.vedaconsulting.mailchimp#135]
How to recreate.
1. Create list in mailchimp
2. Grouping labled mailing list
3. Add two groups named list1 and list 2
4. In CiviCRM create two groups named list1 and list2
5. Map civicrm list1 to mailchimp list1 and civicrm list2 to mailchimp list2
6. add member subscriber to both list1 and list2 groups in civicrm
7. look at mailchimp to see if both groups are checked.

**Comment by veda-consulting** [comment]
@trackleft step 7 should be to run the mailchimp sync scheduled job and then step 8 would be to check the groups. Could you try this and let us know if it still occurs?

**Comment by deepak-srivastava** [comment]
Closing old ticket. Please re-open if the original query still exists in relation to v2.x release.
