### ISSUE TITLE
Webhook Error

### ISSUE THREAD

**Issue by madurak** [veda-consulting/uk.co.vedaconsulting.mailchimp#136]
Hi,

When I add the webhook URL from Civi to the mailchimp Callback URL field, I get a error as follows: "We couldn't verify the URL is working. Please double check and try again. HTTP Code: 403"

My URL is https://test.co.uk/civicrm/mailchimp/webhook?reset=1&key=test&123

It will be great if you can point me in the right direction on how to solve this.

CiviCRM - 4.5.7
Drupal - 7.35
Mailchimp Extension - 1.7

Thank You!
Madura

**Comment by Kajakaran** [comment]
Hi @madurak ,

It looks that you are not testing webhook with genuine call back URL. 

cc @veda-consulting 

Thanks

**Comment by madurak** [comment]
Hi,
I just wrote it down as test.co.uk instead of the real url (which is our clients) to ask a question here, but when i test it, i use a genuine one.

**Comment by Kajakaran** [comment]
HI @madurak ,

Could you check the web hook URL has the right permission (Mailchimp: allow webhook posts) for Anonymous User?

Thanks

**Comment by madurak** [comment]
Thanks so much, that solved my problem :)
