### ISSUE TITLE
Followup to #121 - unsubscribe via webhook leaves child-groups intact

### ISSUE THREAD

**Issue by jason-vivid** [veda-consulting/uk.co.vedaconsulting.mailchimp#137]
Running 1.7 extension. Screenshot below.  

Steps:  
1. User Unsubscribes in Mailchimp from a list which has multiple interest groups (4 in this case)
     - the list corresponds to a parent group in Civi 
     - the interest groups in Mailchimp correspond to child groups in Civi
2. Webhook fires and removes the Parent group (See arrow #1 in screenshot)
3. Child groups (circled #2) are still listed in the groups tab

![image](https://cloud.githubusercontent.com/assets/10146532/7592805/99a1b37a-f8a3-11e4-9318-bf45095f792f.png)

**Comment by jason-vivid** [comment]
To clarify incase it wasn't if the parent group gets removed the child groups should go with it as well and it is not currently doing this.

**Comment by vajeevan** [comment]
This issue has been fixed in mailchimp extension Version 1.8. Please have a look.

**Comment by veda-consulting** [comment]
@jason-vivid closing, please re-open if its still an issue.
