### ISSUE TITLE
Deleted contacts are being resynced into Mailchimp

### ISSUE THREAD

**Issue by jason-vivid** [veda-consulting/uk.co.vedaconsulting.mailchimp#140]
Some others may want to weigh in on this...

I deleted several users from Civi.  My expectation was that they would be removed in Mailchimp (I don't care whether they are or not, others may). But I did go in and delete them from Mailchimp as well.  

After a Civi > Mailchimp Sync all those deleted contacts that I just deleted were back in Mailchimp.  These were contacts that were "in the trash" and not permanently deleted.

**Comment by jason-vivid** [comment]
I was able to clear this by:

1. remove webhooks on all lists
2. delete contacts in Civi
3. delete contacts in Mailchimp
4. enter webhooks for each list again

after that sync's do not cause contacts to reappear in Mailchimp or Civi.

**Comment by vajeevan** [comment]
This issue has been fixed in mailchimp extension Version 1.8. Please have a look.

**Comment by veda-consulting** [comment]
@jason-vivid closing, please re-open if its still an issue.
