### ISSUE TITLE
sync numbers don't reflect correctly

### ISSUE THREAD

**Issue by jason-vivid** [veda-consulting/uk.co.vedaconsulting.mailchimp#141]
I've noticed our numbers don't seem to make sense at times when we run the civi to mailchimp sync. I just performed a sync followed by a 2nd sync with no changes to the contact records in-between.  I expected that the counts would all reflect no changes, however the list of contacts in sync already was 0 or an insignificant number.

![image](https://cloud.githubusercontent.com/assets/10146532/7595648/43852ed2-f8b6-11e4-9b62-be6208e009c2.png)

**Comment by veda-consulting** [comment]
@jason-vivid we've found why and the latest version will have an extra line, representing data that Mailchimp doesn't accept. You'll be able to click a link and see the exact data. This should also correct the numbers.

**Comment by vajeevan** [comment]
This issue has been fixed in mailchimp extension Version 1.8. Please have a look.

**Comment by veda-consulting** [comment]
Closing
