### ISSUE TITLE
Civi to Mailchimp Sync Error

### ISSUE THREAD

**Issue by jason-vivid** [veda-consulting/uk.co.vedaconsulting.mailchimp#142]
[Error: List 1 LISTNAME: Added new subscribers and updating existing data changes]
API call to lists/batch-subscribe failed: Problem (2) in the Chunked-Encoded data

I get the above when syncing from Civi to Mailchimp.

**Comment by jason-vivid** [comment]
I removed all of our contacts from Mailchimp on this list and ran the sync again.  Civi populated mailchimp with the data, but still threw the error above.  The data appears to reflect what we have in civi.

**Comment by veda-consulting** [comment]
@jason-vivid I'm guessing this is something specific to the data you're syncing. In the new version of the extension (due out this week) we've added the option to have more logging thrown out so you should be able to see in the log files exactly which data is causing this. Once we've identified it we should be able to find the appropriate fix.

**Comment by veda-consulting** [comment]
@jason-vivid we're closing tickets that haven't been active for a while. If you still get this then we've now included some extra debug capabilities in the extension. If you turned that on and check out the log files it might provide some insight into the problem. You could send over to us if you wanted us to have a look.
