### ISSUE TITLE
CIviCRM 4.6

### ISSUE THREAD

**Issue by ddoligalski** [veda-consulting/uk.co.vedaconsulting.mailchimp#143]
Has anyone tried the extension on CiviCRM 4.6?

**Comment by veda-consulting** [comment]
@ddoligalski there are a few, someone created an issue and they were on 4.6 - the issue was resolved by something at their end and no changes to the extension. Maybe give it a try?

**Comment by veda-consulting** [comment]
Closing - tested in 4.6 and proved working fine.

**Comment by shawnholt** [comment]
Does not show up in extension directory: #157

**Comment by veda-consulting** [comment]
@shawnholt release was being blocked due to an error in the info.xml file, this has been corrected now so expect to see it in extension directory by tomorrow
