### ISSUE TITLE
Nothing to pull. 

### ISSUE THREAD

**Issue by bkerensa** [veda-consulting/uk.co.vedaconsulting.mailchimp#146]
On CiviCRM 4.6 I get "Nothing to pull. Make sure mailchimp settings are configured in the setting page."

I have the right API Key set and have hundreds of contacts in MailChimp but they wont import?

**Comment by vajeevan** [comment]
@bkerensa Could you tell us what steps have you done? Did you map any CiviCRM groups with Mailchimp lists ?

**Comment by veda-consulting** [comment]
@bkerensa  closing as not heard anything back. Please create a new issue with details of your configuration and steps to reproduce if your still having the issue.
