### ISSUE TITLE
Mailchimp unsubscribes are not being updated in CiviCRM group

### ISSUE THREAD

**Issue by vishram74** [veda-consulting/uk.co.vedaconsulting.mailchimp#147]
I tested unsubscribing a contact from a Mailchimp list but the contact in teh corresponding group in CiviCRM is still in the group and there is no update to "no bulk emails"

I added a new subscriber to MC and this is being added correctly to the group in CiviCRM so I dont think its a problem with the webhook.  Am I missing something?

**Comment by vajeevan** [comment]
This issue has been fixed in mailchimp extension Version 1.8. Now, the contacts will be removed from the corresponding CiviCRM groups mapped with mailchimp groups, if a contact is unsubscribed in a mailchimp list. Please have a look.

**Comment by veda-consulting** [comment]
Closing
