### ISSUE TITLE
DB Error: syntax error - in Manage Groups

### ISSUE THREAD

**Issue by rollox** [veda-consulting/uk.co.vedaconsulting.mailchimp#150]
After a fresh install and configuring "Mailchimp Settings" correctly; clicking the down arrow to show child groups in Manage Groups screen throws "DB Error: syntax error".

Versions and Backtrace follow...

Mailchimp Extension 1.8
CiviCRM 4.4.16
Drupal 6.36
MySQL 5.5.42
PHP 5.3.29

$backTrace = #0 /dir/sites/all/modules/civicrm/CRM/Core/Error.php(777): CRM_Core_Error::backtrace("backTrace", TRUE) 
#1 [internal function](): CRM_Core_Error::exceptionHandler(Object(DB_Error)) 
#2 /dir/sites/all/modules/civicrm/packages/PEAR.php(931): call_user_func((Array:2), Object(DB_Error)) 
#3 /dir/sites/all/modules/civicrm/packages/DB.php(969): PEAR_Error->PEAR_Error("DB Error: syntax error", -2, 16, (Array:2), "\n SELECT entity_id, mc_list_id, mc_grouping_id, mc_group_id, is_mc_upd...") 
#4 /dir/sites/all/modules/civicrm/packages/PEAR.php(564): DB_Error->DB_Error(-2, 16, (Array:2), "\n SELECT entity_id, mc_list_id, mc_grouping_id, mc_group_id, is_mc_upd...") 
#5 /dir/sites/all/modules/civicrm/packages/DB/common.php(1905): PEAR->raiseError(NULL, -2, NULL, NULL, "\n SELECT entity_id, mc_list_id, mc_grouping_id, mc_group_id, is_mc_upd...", "DB_Error", TRUE) 
#6 /dir/sites/all/modules/civicrm/packages/DB/mysql.php(898): DB_common->raiseError(-2, NULL, NULL, NULL, "1064 ** You have an error in your SQL syntax; check the manual that correspon...") 
#7 /dir/sites/all/modules/civicrm/packages/DB/mysql.php(327): DB_mysql->mysqlRaiseError() 
#8 /dir/sites/all/modules/civicrm/packages/DB/common.php(1216): DB_mysql->simpleQuery("\n SELECT entity_id, mc_list_id, mc_grouping_id, mc_group_id, is_mc_upd...") 
#9 /dir/sites/all/modules/civicrm/packages/DB/DataObject.php(2434): DB_common->query("\n SELECT entity_id, mc_list_id, mc_grouping_id, mc_group_id, is_mc_upd...") 
#10 /dir/sites/all/modules/civicrm/packages/DB/DataObject.php(1626): DB_DataObject->_query("\n SELECT entity_id, mc_list_id, mc_grouping_id, mc_group_id, is_mc_upd...") 
#11 /dir/sites/all/modules/civicrm/CRM/Core/DAO.php(160): DB_DataObject->query("\n SELECT entity_id, mc_list_id, mc_grouping_id, mc_group_id, is_mc_upd...") 
#12 /dir/sites/all/modules/civicrm/CRM/Core/DAO.php(908): CRM_Core_DAO->query("\n SELECT entity_id, mc_list_id, mc_grouping_id, mc_group_id, is_mc_upd...", TRUE) 
#13 /dir/sites/all/extensions/uk.co.vedaconsulting.mailchimp/CRM/Mailchimp/Utils.php(61): CRM_Core_DAO::executeQuery("\n SELECT entity_id, mc_list_id, mc_grouping_id, mc_group_id, is_mc_upd...", (Array:0)) 
#14 /dir/sites/all/extensions/uk.co.vedaconsulting.mailchimp/api/v3/Mailchimp.php(153): CRM_Mailchimp_Utils::getGroupsToSync((Array:38)) 
#15 /dir/sites/all/modules/civicrm/api/api.php(88): civicrm_api3_mailchimp_getcivicrmgroupmailchimpsettings((Array:4)) 
#16 /dir/sites/all/modules/civicrm/CRM/Utils/REST.php(361): civicrm_api("Mailchimp", "getcivicrmgroupmailchimpsettings", (Array:4)) 
#17 /dir/sites/all/modules/civicrm/CRM/Utils/REST.php(588): CRM_Utils_REST::process((Array:3), (Array:2)) 
#18 [internal function](): CRM_Utils_REST::ajax((Array:3)) 
#19 /dir/sites/all/modules/civicrm/CRM/Core/Invoke.php(293): call_user_func((Array:2), (Array:3)) 
#20 /dir/sites/all/modules/civicrm/CRM/Core/Invoke.php(76): CRM_Core_Invoke::runItem((Array:12)) 
#21 /dir/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:3)) 
#22 /dir/sites/all/modules/civicrm/drupal/civicrm.module(405): CRM_Core_Invoke::invoke((Array:3)) 
#23 [internal function](): civicrm_invoke("ajax", "rest") 
#24 /dir/includes/menu.inc(350): call_user_func_array("civicrm_invoke", (Array:2)) 
#25 /dir/index.php(17): menu_execute_active_handler() #26 
{main}

**Comment by veda-consulting** [comment]
@rollox thanks for the report, we'll take a look.

**Comment by krishgopi** [comment]
This issue has been fixed in mailchimp extension Version 1.8.1.  Please have a look.

**Comment by veda-consulting** [comment]
@rollox closing, please re-open if its still occurs. 1.8.1. will be released tonight.

**Comment by rollox** [comment]
Yes, thanks for fixing @krishgopi. Presumably 1.8.1 will be made available:
https://civicrm.org/extensions/mailchimp-civicrm-integration

**Comment by rollox** [comment]
No errors thrown now but I notice a minor display issue in the html rendering of the group table containing the Mailchimp List and Mailchimp Group data fields.

Multiple columns appear in the root group records in the table for each click of any parent (drop down arrow).

ie click once and you get:

Mailchimp List
Mailchimp Group
Mailchimp List
Mailchimp Group

Where there should only be two columns:

Mailchimp List
Mailchimp Group

This also misaligns parent/child group records.
