### ISSUE TITLE
Sync limited to 25 MailChimp Lists

### ISSUE THREAD

**Issue by ddoligalski** [veda-consulting/uk.co.vedaconsulting.mailchimp#155]
We have run into an installation of the extension that is trying to sync to more than 25 lists in MailChimp.  

In reviewing the extension code we note that there is a default limit of 25 set in the declaration of the getList function in vendor/mailchimp/Mailchimp/Lists.php.  

The code that calls the getList function in api/v3/Mailchimp.php however does not provide an override to the limit so the 25 limit sticks.

I'm not quite sure of the proper way to handle this.  An arbitrary higher value could be used, but then it risks getting hit as well.  Probably the calls to getList in api/v3/Mailchimp.php need to check for more lists available.

Thanks!

-Dave

**Comment by veda-consulting** [comment]
@ddoligalski we'll take a look and come back to you.

**Comment by anumgoel** [comment]
We at BackOffice Thinking will be happy to spend few hours to fix this issue and then we can send you the pull request. Please do let us know.

Thanks

-Anum Goel

**Comment by veda-consulting** [comment]
@anumgoel hey, if you can that would be great. Issue the PR and we'll take a look.

**Comment by anumgoel** [comment]
Sure! Thanks

**Comment by veda-consulting** [comment]
@anumgoel just checking if you've moved on this?

**Comment by anumgoel** [comment]
Yes, we worked on the fix and we're testing it on our site, I should be able to send you pull request very soon.

**Comment by veda-consulting** [comment]
@anumgoel ok cool thanks

**Comment by anumgoel** [comment]
Hi - I just issued PR for this issue - https://github.com/veda-consulting/uk.co.vedaconsulting.mailchimp/pull/158/files

Thanks

**Comment by twomice** [comment]
This fix works for me on a site with 32 lists (i.e. looks good for greater than 25, but I can't confirm anything for greater than 100). Thanks, Anum!

**Comment by veda-consulting** [comment]
Closing - other reports also show this is working
