### ISSUE TITLE
Update Readme to reflect update functionality: re-add contact to Civi group and is re-subscribed in MailChimp

### ISSUE THREAD

**Issue by herbdool** [veda-consulting/uk.co.vedaconsulting.mailchimp#160]
You said in the README: "Mailchimp treats unsubscribed people in a bit of a permanent way; you cannot ever re-subscribe them!" However, in 1.8.2 (and earlier?) we've noticed in our testing that in fact if a contact is re-added to a group in CiviCRM that the contact is re-subscribed in Mailchimp immediately (no sync button nor cron).

So that makes it a bit easier for people I imagine.

Full section from README:

> Note: currently, removals are processed as unsubscribes from Mailchimp. This is so that Mailchimp's reporting and subscriber history is not affected by removals. However, Mailchimp treats unsubscribed people in a bit of a permanent way; you cannot ever re-subscribe them! This is caution on Mailchimp's part, as they have to ensure their service is not used by spammers. However it's an awkward feature for the general integration case. The only way to re-subscribe someone who previously unsubscribed is to first delete them from the Mailchimp list.
> 
> We have an upcoming feature that will give you the option to force a CiviCRM to Mailchimp sync which will automatically do the necessary deletions, but this is not included in the current version. Watch this space.

**Comment by deepak-srivastava** [comment]
We think latest v2.x has fixed this. Please re-open if the issue still exist. Thanks.
