### ISSUE TITLE
Removed from smart group when Mailchimp sync runs

### ISSUE THREAD

**Issue by natsukipope** [veda-consulting/uk.co.vedaconsulting.mailchimp#165]
Hi, one of our clients have the issue that a contact in smart group is removed when Mailchimp sync runs. 
1. A contact is added to a smart group. "Sync membership of this group with membership of a Mailchimp List" is set up for an appropriate list in Mailchimp. 
2. Run "Mailchimp Sync" in scheduled jobs. Confirm that the contact is added into the mailing list in Mailchimp side. Then go back to check the contact's info in Civi. This person is removed from the smart group. 
3. Run "Mailchimp Sync" again. Since the contact is removed from the smart list, the person is also removed from Mailchimp list, and it is marked as "Reason: N/A (Unsubscribed by an admin)". Screenshot attached. 
   <img width="635" alt="screen shot 2015-10-27 at 15 32 53" src="https://cloud.githubusercontent.com/assets/13272670/10763086/822cf186-7cc0-11e5-80c6-459fb055fcb6.png">

Originally this issue was found in Mailchimp 1.7. We've just updated CiviCRM to 4.6.9 and Mailchimp extension to 1.8.2 but it didn't solve the issue. 

Appreciate your help in advance. 
Natsuki

**Comment by veda-consulting** [comment]
@natsukipope please check the Webhook settings on the Mailchimp side. The one which sends information back to CiviCRM should *NOT* be set to execute on API calls. We think this is the issue. Also the latest version 1.8.3 has a failsafe built into it to highlight this configuration

**Comment by natsukipope** [comment]
Hi, thank you for your reply. 
So when I went to mailchimp.com/lists/tools/webhooks ... page, for the test site there was no Webhook created. And for the actual client site, Only send updates when a change is made …  via the API was unchecked. 
<img width="390" alt="screen shot 2015-10-28 at 10 42 09" src="https://cloud.githubusercontent.com/assets/13272670/10821983/f168945a-7e4c-11e5-8196-6c6909b1fe5a.png">

The issue happens in both sites. Anything else I could check?

**Comment by veda-consulting** [comment]
@natsukipope is this still an issue for you? Could you update to the latest version and let us know if its still happening?

**Comment by deepak-srivastava** [comment]
We think latest v2.x has fixed this. Please re-open if the issue still exist. Thanks.
