### ISSUE TITLE
Webhook not updating info in Civi after updating to 1.8.3

### ISSUE THREAD

**Issue by jason-vivid** [veda-consulting/uk.co.vedaconsulting.mailchimp#167]
Mailchimp is firing the webhook, however when it hits the server nothing is being updated.  Here is the log info.

Nov 17 17:55:58  [info] $CRM_Mailchimp_Page_WebHook run $my_key=  = 1234

Nov 17 17:55:58  [info] $Fatal Error Details = Array
(
    [message] =>
    [code] =>
)

Nov 17 17:55:58  [info] $backTrace = #0 /srv/www/sites/all/modules/civicrm/CRM/Core/Error.php(363): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 /srv/www/civi-extensions/uk.co.vedaconsulting.mailchimp-1.8.3/CRM/Mailchimp/Page/WebHook.php(16): CRM_Core_Error::fatal()
#2 /srv/www/sites/all/modules/civicrm/CRM/Core/Invoke.php(312): CRM_Mailchimp_Page_WebHook->run((Array:3), NULL)
#3 /srv/www/sites/all/modules/civicrm/CRM/Core/Invoke.php(86): CRM_Core_Invoke::runItem((Array:14))
#4 /srv/www/sites/all/modules/civicrm/CRM/Core/Invoke.php(54): CRM_Core_Invoke::_invoke((Array:3))
#5 /srv/www/sites/all/modules/civicrm/drupal/civicrm.module(489): CRM_Core_Invoke::invoke((Array:3))
#6 [internal function](): civicrm_invoke("mailchimp", "webhook")
#7 /srv/www/includes/menu.inc(519): call_user_func_array("civicrm_invoke", (Array:2))
#8 /srv/www/index.php(21): menu_execute_active_handler()
#9 {main}

**Comment by Kajakaran** [comment]
HI @jason-vivid 

It looks like you are missing step 3(“allow webhook posts” permission not set to anonymous user) in basic use in extension readme file.(https://github.com/veda-consulting/uk.co.vedaconsulting.mailchimp/blob/master/README.md)

cc - @veda-consulting

**Comment by veda-consulting** [comment]
@jason-vivid  have you been able to confirm this is your issue? We'll close it if we don't hear back....

**Comment by jason-vivid** [comment]
Yes.  Please close.  Thanks for the help.
