### ISSUE TITLE
scheduled job: only supports MC precedence

### ISSUE THREAD

**Issue by lcdservices** [veda-consulting/uk.co.vedaconsulting.mailchimp#171]
The scheduled job that ships with recent version of this tool, as indicated in the job description, always pulls from MC before pushing to MC. That means that contacts added to the synced group in CiviCRM are **always** removed the group, and never pushed to MC. It also means that the only way to keep the MC list updated from the CiviCRM group is to manually sync from Civi to MC before doing a mailing.

I appreciate that a two-way sync is always a bit tricky, as you need to decide which data set will be the "master," but in this case it doesn't seem to make sense:
- as noted above, the current behavior makes it impossible to add contacts to the MC group via CiviCRM.
- the documentation for the extension indicates that after an initial sync, it's generally not necessary to ever sync from MC to CiviCRM, because the webhook takes care of things. so if anything, it seems you should always do a CiviCRM to MC sync because the reverse is not needed very often

I'm wondering what the rationale was for the current behavior, and whether there are thoughts/plans to provide a similar job, or options to pass to the job, so that the order of operation is reversed.

**Comment by Kajakaran** [comment]
Hi @lcdservices,

There was a bug which now resolved in 1.8.5, that is when you create new contact and add to CiviCRM synced group which instantly mapped to Mailchimp lists/groups. This is done via CiviCRM post hook.

can you please test and let us know outcome?

Thanks

**Comment by deepak-srivastava** [comment]
We think latest v2.x has fixed this. Please re-open if the issue still exist. Thanks.
