### ISSUE TITLE
webhook url returning 'null' in browser and 403 error in Mailchimp

### ISSUE THREAD

**Issue by ianemcallister** [veda-consulting/uk.co.vedaconsulting.mailchimp#172]
I've been struggling with this all weekend and haven't been able to find the right fix.   I’m trying to setup webhooks for Mailchimp and CiviCRM 4.6.1 through Wordpress 4.3.1. 

The mailchimp settings panel in CiviCRM provides the web hook address as:

Webhook URL - http://<domain>/?page=CiviCRM&q=civicrm/mailchimp/webhook&reset=1&key=2345

Anytime I request the url in a browser window it returns a ‘null’ response.  When I paste it into the Mailchimp webhook setup Mailchimp gives me a 403 error (“We couldn't verify the URL is working. Please double check and try again. HTTP Code: 403”).

Step 3 of veda-consulting's instructions is 'Make sure webhook url is accessible to public. If not, just make sure anonymous / public user has “allow webhook posts” permission. ' but in wordpress settings (https://en.support.wordpress.com/webhooks/#what-would-i-use-something-like-this-for) I can’t find a webhook tool. Am I missing something? Is this from an older version of wordpress.  I found the Hookpress plugin but it has a warning that it hasn’t been tested with the current version of wordpress.

I feel like I've read everyone's questions in this area and haven't found the right solution yet.  Really appreciate it!

**Comment by Kajakaran** [comment]
@ianemcallister 

You can enable 'allow webhook posts' permission in wordpress access control by navigating to

http://<your domain>/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fadmin%2Faccess%2Fwp-permissions&reset=1

Then it will solve 403 error

![wordpress_permision](https://cloud.githubusercontent.com/assets/7429798/11624857/8fac6e3a-9cce-11e5-9395-488fa10189e3.png)


cc- @veda-consulting

**Comment by ianemcallister** [comment]
Thanks for the speedy response Kajakaran! I hadn't seen that interface before.  I made the change you requested, though I'm still getting a 'null' response from the link and a 403 error in Mailchimp.  Could there be something else I'm glossing over?  Thanks!

**Comment by ianemcallister** [comment]
Not a totally satisfying answer but I ran my webhook link through firebug and it always returns an ok 200 response from the server.

I corresponded with Mailchimp and they confirmed that from what they can see there isn't an issue with the webhook I'm using.  They suggested I whitelist their API's IP addresses but my hosting doesn't allow whitelist IPs.  I've gone back to Mailchimp but it's looking like the fate is sealed on this one.

**Comment by veda-consulting** [comment]
Its a really strange issue, not had it from anyone else. There must be some
communication problem between Mailchimp and your server but its out of our
control really.



Veda Consulting
t : +44 (0) 20 3239 1156
m : +44 (0) 77 4216 3491
e : parvez@vedaconsulting.co.uk
w : www.vedaconsulting.co.uk

**Comment by deepak-srivastava** [comment]
Closing this one. Please reopen if problem still exists or file a new one.
