### ISSUE TITLE
Webhook and API updates

### ISSUE THREAD

**Issue by jason-vivid** [veda-consulting/uk.co.vedaconsulting.mailchimp#175]
We have recently added an API to one of our sites that pushes newly captured email addresses into Mailchimp.  Right now we have the setting "Only send updates when a change is made … via the API" turned off.  I believe there are only two ways to get these updates into CiviCRM.  One is to have a scheduled job run and pull them in or the second would be to turn on "via the API" updates.  

Is there anything that prevents me from turning on the "via the API" updates? Are there any known issues with this or reasons not to?

**Comment by veda-consulting** [comment]
@jason-vivid when CiviCRM updates Mailchimp it uses the Mailchimp API. If you left the "via API" checked then Mailchimp would attempt to send the updated back to CiviCRM which would effectively cause an infinite loop. We have had reports of others accidentally setting this checkbox and experience odd behaviour on their sites. We've also added some checks to the CiviCRM Mailchimp configuration page to warn if this checkbox has been ticked in Mailchimp.
