### ISSUE TITLE
Mailchimp and Civicrm under Joomla

### ISSUE THREAD

**Issue by jorich-2000** [veda-consulting/uk.co.vedaconsulting.mailchimp#177]
I am running Joomla 3.4.6, CiviCRM 4.6.10 and Mailchimp Integration 1.8.5
The integration works fine for syncing contacts from Civi to Mailchimp but I cant get the webhooks to work.
Mailchimp extension says webhook is at https://myserver.org.uk/index.php?option=com_civicrm&task=civicrm/mailchimp/webhook&reset=1&key=xxxxxxxxxx but this page returns a CIVICRM error 0 page
This looks like it might be a Joomnla ACl issue - many other people seem to have similar problems but there is no proper Joomla information available
I am happy to work on this with you

**Comment by Kajakaran** [comment]
@jorich-2000 

Please follow instruction on https://github.com/veda-consulting/uk.co.vedaconsulting.mailchimp/issues/187

Thanks

**Comment by deepak-srivastava** [comment]
Closing old ticket. Please re-open if the original query still exists in relation to v2.x release.
