### ISSUE TITLE
Webhook Url: 404 Error in MailChimp

### ISSUE THREAD

**Issue by envirokid** [veda-consulting/uk.co.vedaconsulting.mailchimp#178]
Hello,
I have been trying to setup webhooks for Mailchimp and CiviCRM 4.6.10 through Wordpress 4.3.2 following the instructions provided here: https://github.com/veda-consulting/uk.co.vedaconsulting.mailchimp

The Mailchimp settings in CiviCRM provides me with this webhook address (I have taken out our actual domain name & key in asking this question): 
http://www.domain.org/civicrm?page=CiviCRM&q=civicrm/mailchimp/webhook&reset=1&key=testkey123

When I submit this in Google Chrome, it provides me with 'null'. I tried it in Firefox and was provided with a blank page on our website with the tab reading "Nothing found for Civicrm?pa..." When I paste it into the Mailchimp webhook setup, I am provided with "We couldn't verify the URL is working. Please double check and try again. HTTP Code: 404".

I've been combing through other posts here and whatever I find using Google. My "allow webhook posts" permissions for anonymous/public are set properly as well, which seemed to solve some others' problems, but mine continues to show up with these same errors. Someone told me that a 404 probably means the callback URL I input doesn't exist, but it was the one provided.

Any suggestions for how to proceed would be greatly appreciated. Thank you!

**Comment by veda-consulting** [comment]
We're in the process of testing out a wordpress site at the moment and are
seeing the same issue, we'll look into it and come back with a fix.



Veda Consulting
t : +44 (0) 20 3239 1156
m : +44 (0) 77 4216 3491
e : parvez@vedaconsulting.co.uk
w : www.vedaconsulting.co.uk

**Comment by envirokid** [comment]
Hello! Just checking in. Any luck with this?

**Comment by Kajakaran** [comment]
Hi @envirokid 

Do you have CiviCRM page on your WordPress site?
Follow the link 
https://github.com/veda-consulting/uk.co.vedaconsulting.mailchimp/blob/master/images/wordpress_civi_default_page.png

**Comment by envirokid** [comment]
Yes! I saw that it is on private. I changed it to Public and it worked. Is that what I was supposed to do or would you suggest Password Protected (if that works)? 

Thank you!

**Comment by Kajakaran** [comment]
@envirokid 

Webhook URL should be accessible by anonymous user which means public URL.

The following link might be helpful regarding public URL on WordPress sites.
https://wiki.civicrm.org/confluence/display/CRMDOC/Displaying+Public+Forms+in+WordPress+Frontend+Sites
