### ISSUE TITLE
Update documenation (readme) to clarify support of duplicate contacts

### ISSUE THREAD

**Issue by shawnholt** [veda-consulting/uk.co.vedaconsulting.mailchimp#181]
Please include any limitations when dealing with duplicate email contacts.  I've seen some confusion on this in issue and what is supported.  Perhaps note that de-duplication matching is not performed and what happens if there are duplicate emails (e.g. only the first will match on bounce.)
ref: #134 #133 #94 #55

**Comment by deepak-srivastava** [comment]
We think latest v2.x has fixed this. Please re-open if the issue still exist. Thanks.
