### ISSUE TITLE
Error: Failed to access Mailchimp export API

### ISSUE THREAD

**Issue by groston** [veda-consulting/uk.co.vedaconsulting.mailchimp#182]
(Drupal 7.41, CiviCEM 4.6.8, Mailchimp Sync: 1.8)

I clicked Mailchimp Sync earlier today and was presented with the following error:

[Error: List 1 All Contacts: Fetched data from Mailchimp]
Failed to access Mailchimp export API

I noticed that my extension was out-of-date, so I just updated it and tried again, and got the same result. I have used this extension many times in the past without problem, and other than basic updates, there have been no changes to the system. Can anyone suggest why this problem has 'suddenly' arisen?

**Comment by veda-consulting** [comment]
Hi - Sounds like a permission error i.e. your mailchimp account API
credentials aren't correct?



Veda Consulting
t : +44 (0) 20 3239 1156
m : +44 (0) 77 4216 3491
e : parvez@vedaconsulting.co.uk
w : www.vedaconsulting.co.uk

**Comment by groston** [comment]
Parvez,

 

Thanks for the response. I checked and the credentials are find (and unchanged). 

 

I just looked in the CiviCRM error log and found this:

 

Jan 14 21:08:41  [info] $CRM_Queue_Page_AJAX_runNext_error = Exception: "Failed to access Mailchimp export API"

#0 /home/neftempo/public_html/sites/default/files/civicrm/custom_ext/uk.co.vedaconsulting.mailchimp-master/CRM/Mailchimp/Form/Sync.php(187): CRM_Mailchimp_Form_Sync::syncCollectMailchimp("20076478a6")

#1 [internal function](): CRM_Mailchimp_Form_Sync::syncPushCollectMailchimp(Object(CRM_Queue_TaskContext), "20076478a6")

#2 /home/neftempo/public_html/sites/all/modules/civicrm/CRM/Queue/Task.php(88): call_user_func_array((Array:2), (Array:2))

#3 /home/neftempo/public_html/sites/all/modules/civicrm/CRM/Queue/Runner.php(213): CRM_Queue_Task->run(Object(CRM_Queue_TaskContext))

#4 /home/neftempo/public_html/sites/all/modules/civicrm/CRM/Queue/Page/AJAX.php(52): CRM_Queue_Runner->runNext(TRUE)

#5 /home/neftempo/public_html/sites/all/modules/civicrm/CRM/Queue/ErrorPolicy.php(106): CRM_Queue_Page_AJAX::{closure}()

#6 /home/neftempo/public_html/sites/all/modules/civicrm/CRM/Queue/Page/AJAX.php(54): CRM_Queue_ErrorPolicy->call(Object(Closure))

#7 [internal function](): CRM_Queue_Page_AJAX::runNext()

#8 /home/neftempo/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(278): call_user_func((Array:2))

#9 /home/neftempo/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(86): CRM_Core_Invoke::runItem((Array:13))

#10 /home/neftempo/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(54): CRM_Core_Invoke::_invoke((Array:4))

#11 /home/neftempo/public_html/sites/all/modules/civicrm/drupal/civicrm.module(489): CRM_Core_Invoke::invoke((Array:4))

#12 [internal function](): civicrm_invoke("queue", "ajax", "runNext")

#13 /home/neftempo/public_html/includes/menu.inc(527): call_user_func_array("civicrm_invoke", (Array:3))

#14 /home/neftempo/public_html/index.php(21): menu_execute_active_handler()

#15 {main}

 

Does this help point you in the right direction?

 

----

 

Gerry Roston

 <mailto:Gerry@PairOfDocs.net> Gerry@PairOfDocs.net

734-516-6715

**Comment by veda-consulting** [comment]
Hi - So the problem is pretty clearly stated

"Failed to access Mailchimp export API"

This is basically saying CiviCRM cant access mailchimp. Have ports on the
server changed etc? As you've said, this all works fine, so something must
have changed configuration wise.



Veda Consulting
t : +44 (0) 20 3239 1156
m : +44 (0) 77 4216 3491
e : parvez@vedaconsulting.co.uk
w : www.vedaconsulting.co.uk

**Comment by groston** [comment]
Parvez,

 

I am struggling to understand why this error is occurring.

 

The error is being reported as coming from Sync.php line 187, which is a call to syncCollectMailchimp($listID). The error message does indeed come from within this function, so that makes sense. What I don’t get is the following:

 

I checked the database and the ListID is 20076478a6 (as shown below). I also checked in the database and found that the correct API key is stored. Looking Sync.php, lines 391-397, I manually created $url and pasted this values into the address bar of my browser. When I sis this, I received an appropriate response, i.e., a list of names and email addresses.

 

Obviously, I did the above from my computer and not the server on which our website resides. 

 

Can you suggest a next step for me to try in order to resolve this problem?

 

----

 

Gerry Roston

 <mailto:Gerry@PairOfDocs.net> Gerry@PairOfDocs.net

734-516-6715

**Comment by groston** [comment]
Parvez,

 

I did some more digging and have found the underlying problem: On my shared server, allow_url_fopen has been set to off. If the hosting company does not turn this on, how can we modify the code at line 339 of Sync.php to work around this?

 

----

 

Gerry Roston

 <mailto:Gerry@PairOfDocs.net> Gerry@PairOfDocs.net

734-516-6715

**Comment by groston** [comment]
Parvez,

 

Last email: The host enabled allow_url_fopen and everything is working as it should. Thanks for pointing me in the right direction.

 

----

 

Gerry Roston

Gerry@PairOfDocs.net

734-516-6715

**Comment by veda-consulting** [comment]
Thats great Gary - we'll take a look as to ensuring the extension notifies
of this issue on the setup page so that others don't have to go through the
same pain you did. Thanks for pursuing and identifying a hosting issue!



Veda Consulting
t : +44 (0) 20 3239 1156
m : +44 (0) 77 4216 3491
e : parvez@vedaconsulting.co.uk
w : www.vedaconsulting.co.uk

**Comment by deepak-srivastava** [comment]
We think latest v2.x has fixed this. Please re-open if the issue still exist. Thanks.
