### ISSUE TITLE
php memory leak during sync + reporting

### ISSUE THREAD

**Issue by sunilpawar** [veda-consulting/uk.co.vedaconsulting.mailchimp#184]
1.
when large number of contact collected in tmp_mailchimp_push_c table, Contact and Email dao object used to check each contact /email settings are valid (under function syncPushCollectCiviCRM )
1. During sync error_details were stored in civicrm_settings table, it has limitation when data size big and it stuck when we update the stats.
2. Reporting for error details : when there are nested group for same list id, primary group present in url, this will give less records as compared to count mentioned in result screen.

**Comment by deepak-srivastava** [comment]
@sunilpawar I'm assuming following PRs have resolved it already (or to large extent)?
https://github.com/veda-consulting/uk.co.vedaconsulting.mailchimp/pull/189
https://github.com/veda-consulting/uk.co.vedaconsulting.mailchimp/pull/185

**Comment by deepak-srivastava** [comment]
Think this has been resolved. Please re-open if the issue still seem to exist with v2.x. Thanks.
