### ISSUE TITLE
Error: Mail chimp/CiviCRM with Joomla

### ISSUE THREAD

**Issue by jgentles** [veda-consulting/uk.co.vedaconsulting.mailchimp#186]
I'm running Joomla 3.5.4, CiviCRM 4.6.12 and MailChimp/CiviCRM 1.8.6. I've setup a smart group for syncing with Mailchimp. 

I set the MailChimp settings within the Smart Group to 'Sync membership of with a Mailchimp interest grouping'. I select my MailChimp list and then select my MailChimp group (both of which I do see my lists and groups within MailChimp). When I click Save, I get the error message 

"Please correct the following errors in the form fields below:
The list you selected does not have a membership group set up. You must set up a group to track membership of the Mailchimp list before you set up group(s) for the lists interest groupings."

Once the error message appears, it removes the group list that was stored prior to the Save.
Am I missing a setting? Any assistance would be appreciated.

Sincerely,
Janice

![group-settings- mailchimp-mom mentum-members](https://cloud.githubusercontent.com/assets/1371962/13030883/6cb74e9c-d287-11e5-89cd-4a2e0d0cf1f2.png)

**Comment by veda-consulting** [comment]
Hi Janice

I would check the list is in fact a valid list and not one thats been
archived on the mailchimp side of things? It feels like a config issue. Let
us know if that doesn't yeild any results and I can get one of our team to
give you a hand.

Thanks



Veda Consulting
t : +44 (0) 20 3239 1156
m : +44 (0) 77 4216 3491
e : parvez@vedaconsulting.co.uk
w : www.vedaconsulting.co.uk

**Comment by jgentles** [comment]
Thank you very much for your reply.
It is a valid mailing list within MailChimp as that is the main and only mailing list that we use for our campaigns.

Sincerely,
[cid:image001.png@01D0C4A6.4AE45E80]
[jgj-signature]

:: Janice Gentles-Jones
:: Web Technology Consultant
:: JGJ Consulting
:: (516) 333-6578
:: www.onlinesuccessmap.com<http://www.onlinesuccessmap.com/>

"If you think it's expensive to hire a professional to do the job, wait until you hire an amateur." - Red Adair

**Comment by jgentles** [comment]
Hi,
It is possible to get help on this issue? I am really at a lost of what configuration issue could be causing this problem.

Thank you in advance for any help you can provide.

**Comment by veda-consulting** [comment]
Kajan can you help please



Veda Consulting
t : +44 (0) 20 3239 1156
m : +44 (0) 77 4216 3491
e : parvez@vedaconsulting.co.uk
w : www.vedaconsulting.co.uk

**Comment by Kajakaran** [comment]
Hi @jgentles 

You have to set Main CiviCRM group with 'Mailchimp' List using radio option 2 in Civi group setting.

Follow instruction in 'Basic Use' section (Please have look at the picture) in the following URL.

https://github.com/veda-consulting/uk.co.vedaconsulting.mailchimp/blob/master/README.md

In order to connect your CiviCRM group with Mailchimp List's interesting group you should do above setting first.
@veda-consulting

**Comment by jgentles** [comment]
Thank you for your reply. I did set a main CiviCRM group with MailChimp list using radio option 2. But even after setting those setting, of which my MailChimp list does show and my group list also shows, I still get the  "Please correct the following errors in the form fields below:
 The list you selected does not have a membership group set up. You must
 set up a group to track membership of the Mailchimp list before you set up
 group(s) for the lists interest groupings."

**Comment by Kajakaran** [comment]
@jgentles 

I have installed fresh 
Joomla! 3.4.8
civi 4.7.3 
mailchimp 1.8.6

It worked for me

I would suggest to clear following mailchimp setting database table(civicrm_value_mailchimp_settings) which will clear all your setting related to Mailchimp in civi and try mapping.

@veda-consulting

**Comment by nocabt** [comment]
Hi all,

I'm having the same error on CiviCRM 4.4.5 and WordPress 4.4.2. Here are my settings / errors:

![list_groups_for_newsletter___mailchimp](https://cloud.githubusercontent.com/assets/6577933/14365589/413292dc-fcd4-11e5-8733-ef750d744b74.jpg)
![civicrm_ _floridians_for_alternatives_to_the_death_penalty_ _wordpress](https://cloud.githubusercontent.com/assets/6577933/14365646/664c28a8-fcd4-11e5-8470-eb532fcf1bae.jpg)

Currently I'm only trying this with Smart groups.

**Comment by deepak-srivastava** [comment]
Closing old ticket. Please re-open if the original query still exists in relation to latest v2.x release.

**Comment by gpoole** [comment]
For anyone else experiencing this issue, it seems you actually need _two_ Civi groups to use this feature: one which just syncs contacts to a MailChimp list (using the "Contacts in this group should be subscribed to a Mailchimp List" option) and then a _second_ group which is what sets the specific MailChimp interest group for those same contacts.

A simple configuration that worked for me was to have a "MailChimp" parent group in Civi which syncs users to the list, and then sub-groups in Civi under that which contain the users for each of the corresponding MailChimp interest groups. Each of those sub-groups is set to use the "interest sync" option and the parent uses the "membership sync" option.

My confusion comes from assuming that if I just had a group with the "interest sync" setting, that contacts would automatically be added to the list as well as having their interest set, which seems not to be the case.

Hope that helps clarify!
