### ISSUE TITLE
Webhook permissions in Joomla 3.4.8

### ISSUE THREAD

**Issue by katekleiman** [veda-consulting/uk.co.vedaconsulting.mailchimp#187]
I'm having the same issues as the other folks in this thread, but I have installed the 1.8.6 version of the mail chimp extension. The webhook:
http://www.jgsny.org/index.php?option=com_civicrm&task=civicrm/mailchimp/webhook&reset=1&key=xxxxx
returns a page not found error. I tried changing the path as suggested by another user to http://www.jgsny.org/administrator/index.php?option=com_civicrm&task=civicrm/mailchimp/webhook&reset=1&key=xxxxx. That URL brings me to the Joomla login page, then after login, to a Joomla error page: 
`0 <div id="crm-container" class="crm-container" lang="en" xml:lang="en"> <style type="text/css" media="screen"> @import url(/administrator/components/com_civicrm/civicrm/css/civicrm.css); @import url(/administrator/components/com_civicrm/civicrm/bower_components/jquery-ui/themes/smoothness/jquery-ui.min.css); </style> <div class="messages status no-popup"> <div class="icon red-icon ui-icon-alert"></div> <span class="status-fatal">Sorry but we are not able to provide this at the moment.</span> <div class="crm-section crm-error-message"></div> <p><a href="http://www.jgsny.org/administrator/" title="Main Menu">Return to home page.</a></p> </div> </div> <script language="JavaScript"> function toggle( element ) { var className = element.className; if ( className == 'crm-accordion-wrapper collapsed crm-fatal-error-details-block') { element.className = 'crm-accordion-wrapper crm-fatal-error-details-block'; } else { element.className = 'crm-accordion-wrapper collapsed crm-fatal-error-details-block'; } } </script>`

I'm not sure where to go from here. BTW, it's the first time I've used webhooks, so be gentle!
Thanks

**Comment by Kajakaran** [comment]
@GrannyKat 

Tested on my WAMP SERVER
Joomla! 3.4.8 
CiviCRM 4.7.3
Mailchimp - 1.8.6 

It worked for me 
My webhook URL is http://kajan.fwd.wf/index.php?option=com_civicrm&task=civicrm/mailchimp/webhook&reset=1&key=kajan

When you enter your webhook url(http://www.jgsny.org/index.php?option=com_civicrm&task=civicrm/mailchimp/webhook&reset=1&key=xxxxx) without login in your browser, if you get 'null' as content. Then it means web hook works if not you might have some directory or resource URL setting wrong with CiviCRM.
![resouce_url_setting](https://cloud.githubusercontent.com/assets/7429798/13645027/cd1c4be6-e620-11e5-97da-d6a27cbe8172.png)

Or you might want to check any permission blocking public URL as webhook URL is able to access by anonymous user

@veda-consulting

**Comment by deepak-srivastava** [comment]
Closing old ticket. Please re-open if the original query still exists in relation to v2.x release.
