### ISSUE TITLE
Time/memory issues when syncing huge Mailchimp list to CiviCRM

### ISSUE THREAD

**Issue by johanv** [veda-consulting/uk.co.vedaconsulting.mailchimp#188]
We have a Mailchimp list of 10000+ subscribers. If I want to pull the members to CiviCRM, SyncPullUpdates uses too much time and memory for our server.

**Comment by shawnholt** [comment]
I'm not doing a mailchimp integration but if you can do some profiling in PHP or Drupal it will probably help isolate where the memory is used.

**Comment by johanv** [comment]
I think I am able to fix this. I will look into this, and I will send a pull request if I get this working.

**Comment by johanv** [comment]
I found another problem that was slowing things down a lot, see commit 96a88e4. I added it to the PR.
