### ISSUE TITLE
Compatability with 4.7.x

### ISSUE THREAD

**Issue by rollox** [veda-consulting/uk.co.vedaconsulting.mailchimp#200]
Is this known to be incompatible with 4.7.x?

**Comment by artd** [comment]
Same here. Not working with civicrm 4.7.6

**Comment by GrannyKat** [comment]
Concur - not working with 4.7.7. Any ETA on an update?

**Comment by shawnholt** [comment]
What is the issue?

**Comment by shawnholt** [comment]
Could be related to this: https://civicrm.org/blog/eileen/updating-extensions-for-47

**Comment by Kajakaran** [comment]
@GrannyKat 
I have tested with drupal with civi 4.7.1. I did not see any issues.
can you give more details on your issue?
Thanks
Kajan

**Comment by artd** [comment]
Please Test with 4.7.6 and you will See it is not working anymore also not possible to reinstall

**Comment by shawnholt** [comment]
@artd @GrannyKat - Any chance you can be more specific about "not working"?  Is there an installation error?  Does the menu appear?  Are there errors in the civicrm log file?  I'm sure more detail will help @Kajakaran .

**Comment by artd** [comment]
the extension is even not listed anymore in the extiondirectory of civicrm if you try to add in system

**Comment by mjcarter** [comment]
Also have this issue

**Comment by Kajakaran** [comment]
@mjcarter 
We will test against latest release and will update 
Thanks
Kajan

**Comment by zkrebs** [comment]
Does anyone have an update on this? This is holding us back from upgrading our civi

**Comment by mjcarter** [comment]
@zkrebs - have you tried 4.7.9 or 4.7.10? - I think something may have been temporarily broken in Civi in earlier releases of 4.7x - it's been working for me since upgrading to 4.7.9

**Comment by LarryTX** [comment]
I've got CiviCRM 4.7.9. I was able to get the extension installed and working. However -- when I tried to sync from MailChimp to CiviCRM, it unsubscribed every single person on the MailChimp list! Won't do that again!

**Comment by zkrebs** [comment]
@mjcarter I have not tried it - I have a fairly complicated Civi Event setup on 4.6 and its mostly working with this extension, so I am worried to upgrade it.

@larryTX does Syncing from Civi to Mailcimp work correctly for you?

**Comment by LarryTX** [comment]
It took some work, but in the end, I was able to sync correctly. It pulled all entries from MailChimp over into an empty CiviCRM group. In the process, it does not appear to have duplicated any contacts and correctly assigned the group to existing contacts.

**Comment by deepak-srivastava** [comment]
Think this has been resolved. Please re-open if the issue still seem to exist with latest v2.x. Thanks.
