### ISSUE TITLE
Delete members instead of unsubscribe - Mailchimp API changed

### ISSUE THREAD

**Issue by jake-mw** [veda-consulting/uk.co.vedaconsulting.mailchimp#202]
It appears there was a recent change in the behaviour of the Mailchimp API. As recently as 3 weeks ago, API calls could unsubscribe and resubscribe members at will, which worked well to keep Civi and Mailchimp lists in sync. More recently, trying to re-subscribe an unsubscribed member generates an alert from the Mailchimp API: "test@example.com has unsubscribed, and cannot be resubscribed by you. To prevent false spam complaints, they'll need to resubscribe of their own free will."

This has made the sync process a lot more fragile.

There is a comment in CRM/Mailchimp/Form/Sync.php@217 reading:
`// @todo implement the delete option, here just the unsubscribe is implemented.`

Accordingly, is there any reason we can't change $delete_member from _false_ to _true_ in: 
- MailChimp_Lists::batch_unsubscribe (CRM/Mailchimp/Form/Sync.php@242)
- MailChimp_Lists::unsubscribe (CRM/Mailchimp/Utils.php@775)

This resolves the sync problems I am having, and could be made a configurable option if it's likely to create problems for other users who have different workflows than ours.

I would be happy to put together a pull request if there aren't potential problems here.

**Comment by veda-consulting** [comment]
Hi Jake, yep, thats fine, if you could PR with a configurable setting then
we can review and add to the extension.



Veda Consulting
t : +44 (0) 20 3239 1156
m : +44 (0) 77 4216 3491
e : parvez@vedaconsulting.co.uk
w : www.vedaconsulting.co.uk

**Comment by adam-devapp** [comment]
+1 for this. During the list sync, the following error is displayed: "xxx@xxx.com has unsubscribed, and cannot be resubscribed by you. To prevent false spam complaints, they'll need to resubscribe of their own free will." I was expecting the CiviCRM module to delete the user from the smart group using the web hook.

**Comment by jake-mw** [comment]
PR submitted: #211

**Comment by Kajakaran** [comment]
@jake-mw 

Thanks

It is on our queue. We will verify this PR soon.

**Comment by Kajakaran** [comment]
@jake-mw 
I have tested.

Thanks
Kajan
