### ISSUE TITLE
MailChimp addition not syncing when CiviCRM contact has same email multiple times in same contact

### ISSUE THREAD

**Issue by cmmadmin** [veda-consulting/uk.co.vedaconsulting.mailchimp#203]
(Drupal 7.43, CiviCEM 4.6.14, Mailchimp Sync: 1.8.6)

Adding a subscriber in MailChimp is not syncing to CiviCRM when the contact in CiviCRM has the same email multiple times in the same contact record. I added a new subscriber to a XYZ Group in Mailchimp with email address: xyz@hotmail.com. The subscriber did not appear in the XYZ CiviCRM group.

I see this message in the Civi log:
Apr 13 15:42:22  [info] Mailchimp Pull/Webhook: Multiple contacts found for the email address which is not primary xyz@hotmail.com

In CiviCRM, I have a single contact that has xyz@hotmail.com added to it twice (both as Home Email addresses). When I remove the duplicate Home Email address, then the sync works properly. It appears that the webhook only sees there are two instances of the email in the system but does not see that they are both for the same contact, so it just gives up and the contact is not added to the group in CiviCRM correctly.

This is a major problem for us because our lists are not being updated reliably. Can this be fixed?

**Comment by Kajakaran** [comment]
@cmmadmin 

This issue will be fixed in next release. The work already done to git(https://github.com/veda-consulting/uk.co.vedaconsulting.mailchimp/pull/196/files). In the mean time, you can pull master to test.
