### ISSUE TITLE
Syncing only 1 contact from smart group or group

### ISSUE THREAD

**Issue by adam-devapp** [veda-consulting/uk.co.vedaconsulting.mailchimp#205]
I recently changed the API key to one with more permissions, and it seems the following error keeps being displayed.

"API is set in Webhook setting for listID fbdb2a177xxxx"

If this is just a confirmation, can it be changed to a success, rather than error?

**Comment by Kajakaran** [comment]
@adam-devapp 

This is right error message. API should not be set as option in Web hook setting in Mailchimp.

refer this issue - https://github.com/veda-consulting/uk.co.vedaconsulting.mailchimp/issues/166
