### ISSUE TITLE
Pending subscriptions in CiviCRM still populating MailChimp

### ISSUE THREAD

**Issue by ddoligalski** [veda-consulting/uk.co.vedaconsulting.mailchimp#212]
If CiviMail is configured to Double Opt-In a contact to a Mailing List Group (via a Profile), they are actually added to the group with a "Pending" status.  Once the contact has clicked a link in the opt-in email, their group status is then set to "Added" reflecting the Opt-In.

Currently, the MailChimp extension does not appear to respect the group status, and the pending contacts are added to their corresponding MC groups despite not being (fully) subscribed yet. 

The extension should instead only add a contact when their status is set to "Add".

**Comment by Kajakaran** [comment]
@ddoligalski 

Recent change to get contacts from API changed this behaviour. Could you do a patch to include status?
CRM_Mailchimp_Form_Sync.php
Line 550

Thanks

**Comment by ddoligalski** [comment]
@Kajakaran, I have asked my development team to work on this.

**Comment by Kajakaran** [comment]
Hi,

I have checked on 4.7.1  CiviCRM about this contact get api by passing group id as param

$result = civicrm_api3('Contact', 'get', array( 'group' => $membership_group_id,));

It only gave me contacts with status 'Added'

can you confirm still an issue?

**Comment by deepak-srivastava** [comment]
Closing old ticket. Please re-open if the original query still exists in relation to latest v2.x release.
