### ISSUE TITLE
Getting error when trying to access the settings page in civicrm

### ISSUE THREAD

**Issue by vishram74** [veda-consulting/uk.co.vedaconsulting.mailchimp#217]
We have been running this mailchimp plugin with no issues with Drupal.  We recently upgraded to  CiviCRM 4.6.18.

I tried to do some testing of the plugin to find any issues and when I try and accesst the settings page 
https://<>/civicrm/mailchimp/settings?reset=1.  I get the error below

![mailchimp_error](https://cloud.githubusercontent.com/assets/5449477/16120124/15a01dbe-3411-11e6-8be5-25a4c37c0ac5.png)

Any help would be greatly appreciated
THanks

**Comment by Kajakaran** [comment]
@vishram74 
 Could be related to this 
https://github.com/veda-consulting/uk.co.vedaconsulting.mailchimp/issues/204

Thanks
Kajan

**Comment by vishram74** [comment]
Yes that worked! Thank you @Kajakaran :)
