### ISSUE TITLE
Undefined Offset

### ISSUE THREAD

**Issue by idkelly** [veda-consulting/uk.co.vedaconsulting.mailchimp#221]
Hi There,
Using CiviCRM 4.6.16 on Drupal 7.43 and mailchimp extension 1.87.  I am getting the following error:

Notice: Undefined offset: 0 in CRM_Mailchimp_Form_Setting->buildQuickForm() (line 74 of /home/crm/public_html/sites/all/extensions/uk.co.vedaconsulting.mailchimp-1.8.3/CRM/Mailchimp/Form/Setting.php).

It is being displayed both in the backend and on registration pages.  Has anyone seen this before?
Take Care
Ian

**Comment by Kajakaran** [comment]
@idkelly 
did you try with latest master code?
still an issue?

**Comment by deepak-srivastava** [comment]
Closing old ticket. Please re-open if the original query still exists in relation to latest v2.x release.
