### ISSUE TITLE
WSOD on install of Master on CiviCRM 4.6.15

### ISSUE THREAD

**Issue by zkrebs** [veda-consulting/uk.co.vedaconsulting.mailchimp#223]
Title says it all. Had 1.8.7 installed, disabled, deleted then attempted to install this module. Install goes to WSOD. Thoughts?

**Comment by Kajakaran** [comment]
@zkrebs 
It is worth checking in civicrm log or php error log

Thanks
Kajan

**Comment by deepak-srivastava** [comment]
Closing old ticket. Please re-open if the original query still exists with latest v2.x release.
