### ISSUE TITLE
Coding standards / cleanup

### ISSUE THREAD

**Issue by xurizaemon** [veda-consulting/uk.co.vedaconsulting.mailchimp#230]
Submitting a PR with some coding standards fixes. This so I can then submit PRs which aren't filled with pages of whitespace changes and the like :D

Contains -
- Whitespace, probably lots of it.
- Autoformatting fixes for CiviCRM style (hopefully)
- Remove semicolons in SQL strings
- Other minor style fixes

**Comment by Kajakaran** [comment]
@xurizaemon 

Thanks for your work.

We will review and merge.

**Comment by xurizaemon** [comment]
Thanks. No rush here - I'm currently getting my head around the module and working through the codebase, so will be making a few pushes to that branch.

**Comment by deepak-srivastava** [comment]
Closing this one as the PR has been merged & v2.x is out.
