### ISSUE TITLE
Screen for syncing is non-descriptive and missing the documented "Dry-run" button

### ISSUE THREAD

**Issue by thoni56** [veda-consulting/uk.co.vedaconsulting.mailchimp#236]
I'm trying the sync out on 4.7.x, and it seems to be working, but I'll report issues as I go along. This is the first.

**Comment by Kajakaran** [comment]
Hi
Please have an answer from following issue 
https://github.com/veda-consulting/uk.co.vedaconsulting.mailchimp/issues/229

**Comment by thoni56** [comment]
Ok, the "no dry-run" part is already reported. My point was also that it does not say in which direction it will sync, for example. Even if I is very careful about which menu entry I press, I'd really like a confirmation that I am "dry-running" or running for real.

**Comment by Kajakaran** [comment]
@thoni56 
Thanks for your suggestion. We will add this to our queue.

**Comment by deepak-srivastava** [comment]
Latest v2.x has dry run option. Try it and re-open if still any issues. Thanks.
