### ISSUE TITLE
Provide message parameter in event of API error

### ISSUE THREAD

**Issue by xurizaemon** [veda-consulting/uk.co.vedaconsulting.mailchimp#248]
Provide message for `civicrm_api3_create_error()` in case of error

> Warning: Missing argument 1 for civicrm_api3_create_error(), called in /path/to/civicrm.dev/sites/default/files/civicrm/ext/uk.co.vedaconsulting.mailchimp/api/v3/Mailchimp.php on line 104 and defined in civicrm_api3_create_error() (line 131 of /path/to/civicrm.dev/sites/all/modules/civicrm/api/v3/utils.php).
> Notice: Undefined variable: msg in civicrm_api3_create_error() (line 133 of /path/to/civicrm.dev/sites/all/modules/civicrm/api/v3/utils.php).

**Comment by deepak-srivastava** [comment]
Thanks Chris. Closing this one now. v2.x is out.
