### ISSUE TITLE
Wilma subscribed to too many lists!

### ISSUE THREAD

**Issue by xurizaemon** [veda-consulting/uk.co.vedaconsulting.mailchimp#254]
When executing tests - first time today for this site, returning to work on Mailchimp integrations after a week away.

> `MailchimpApiIntegrationTest::testPullContactWithOtherEmailDiff`
> Exception: There was a problem trying to subscribe this contact at Mailchimp:Mailchimp API said: Invalid Resource (_wilma.flintstone-test-record@example.org has signed up to a lot of lists very recently; we're not allowing more signups for now_)

😬  This may make it tricky to test, if a single test run can trigger Mailchimp's "spammy behaviour" detection. Filing an issue for discussion / in case anyone else can confirm or deny whether this is happening.

NB: Not actually `@example.org` since it seems Mailchimp already detect and reject [RFC2606 SLDs](https://tools.ietf.org/html/rfc2606#section-2) (unfortunately, IMO, they could permit it for [testing accounts](https://twitter.com/ArtfulRobot/status/782857644788871170) perhaps?)

**Comment by deepak-srivastava** [comment]
Closing as the code is merged IN, and v2.x is out.
