### ISSUE TITLE
Issue With Smart Groups 

### ISSUE THREAD

**Issue by stevekessler** [veda-consulting/uk.co.vedaconsulting.mailchimp#256]
While setting up the webhook configuration we (the Cividesk team) identified that the extension could not properly unsubscribe contacts from groups when the top group was a Smart Group.  

|--All Contact With Emails... (Smart Group)
 ---| Group A
 ---| Group B

If the group is not a Smart Group it works perfectly.  

This is not a significant issue but if it is an existing issue it should be corrected in the README file.  

Thanks,
Steve

**Comment by deepak-srivastava** [comment]
Think this has been resolved. Please re-open if the issue still seem to exist with latest v2.x release. Thanks.
