### ISSUE TITLE
Release 2.0 creates problem in CiviCRM groups

### ISSUE THREAD

**Issue by mfuggle** [veda-consulting/uk.co.vedaconsulting.mailchimp#262]
I upgraded to release 2.0 and when I look at the list of groups in CiviCRM it places a new column in the display showing the number of contacts synced to Mailchimp. If I now click on a subsequent column it acts as if it were the column one before it in the list.

**Comment by jorich-2000** [comment]
Same issue here - I found if i right click and copy the link address I can paste it into another tab to still get access to the group settings page for instance

**Comment by matthewduhig** [comment]
Hey guys, same issue here too! 

If you are not fussed about having the extra column, a temp fix is just to remove lines 13 - 23 in Group.extra.tpl file of the extension.

**Comment by zkrebs** [comment]
I also experience this issue and @matthewduhig works as a temporary fix

**Comment by it-foraus** [comment]
we have the same issue (integrate with #288)

**Comment by deepak-srivastava** [comment]
Fixed with #286 (thanks to @kurund). Part of release v2.0.1.
