### ISSUE TITLE
DB Error: unknown error

### ISSUE THREAD

**Issue by pradpnayak** [veda-consulting/uk.co.vedaconsulting.mailchimp#272]
Type	DB_Error
Code	-1
Message	DB Error: unknown error
Mode	16
UserInfo	UPDATE tmp_mailchimp_push_m m INNER JOIN ( SELECT email, c.id AS contact_id FROM civicrm_email e JOIN civicrm_contact c ON e.contact_id = c.id AND c.is_deleted = 0 GROUP BY email HAVING COUNT(DISTINCT c.id)=1 ) uniques ON m.email = uniques.email SET m.cid_guess = uniques.contact_id [nativecode=1055 ** Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'bren_civ.c.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by]
DebugInfo	UPDATE tmp_mailchimp_push_m m INNER JOIN ( SELECT email, c.id AS contact_id FROM civicrm_email e JOIN civicrm_contact c ON e.contact_id = c.id AND c.is_deleted = 0 GROUP BY email HAVING COUNT(DISTINCT c.id)=1 ) uniques ON m.email = uniques.email SET m.cid_guess = uniques.contact_id [nativecode=1055 ** Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'bren_civ.c.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by]

**Comment by pradpnayak** [comment]
PR at https://github.com/veda-consulting/uk.co.vedaconsulting.mailchimp/pull/273

**Comment by deepak-srivastava** [comment]
Thanks @pradpnayak. Is part of v2.0.1.
