### ISSUE TITLE
Deprecated: Group='MailChimp Preferences'. Name='enable_debugging'. Defaults should come from metadata

### ISSUE THREAD

**Issue by pradpnayak** [veda-consulting/uk.co.vedaconsulting.mailchimp#276]
ConfigLog file has below errors and keeps on adding when i try to run push or pull.

Apr 14 07:51:20  [info] Deprecated: Group='MailChimp Preferences'. Name='enable_debugging'. Defaults should come from metadata

Apr 14 07:51:23  [info] Deprecated: Group='MailChimp Preferences'. Name='enable_debugging'. Defaults should come from metadata

Apr 14 07:51:26  [info] Deprecated: Group='MailChimp Preferences'. Name='enable_debugging'. Defaults should come from metadata

Apr 14 07:51:29  [info] Deprecated: Group='MailChimp Preferences'. Name='enable_debugging'. Defaults should come from metadata

Apr 14 07:51:33  [info] Deprecated: Group='MailChimp Preferences'. Name='enable_debugging'. Defaults should come from metadata

Apr 14 07:51:35  [info] Deprecated: Group='MailChimp Preferences'. Name='enable_debugging'. Defaults should come from metadata

Apr 14 07:51:39  [info] Deprecated: Group='MailChimp Preferences'. Name='enable_debugging'. Defaults should come from metadata

Apr 14 07:51:41  [info] Deprecated: Group='MailChimp Preferences'. Name='enable_debugging'. Defaults should come from metadata

Apr 14 07:51:44  [info] Deprecated: Group='MailChimp Preferences'. Name='enable_debugging'. Defaults should come from metadata

Apr 14 07:51:47  [info] Deprecated: Group='MailChimp Preferences'. Name='enable_debugging'. Defaults should come from metadata

**Comment by pradpnayak** [comment]
PR submitted at https://github.com/veda-consulting/uk.co.vedaconsulting.mailchimp/pull/275

**Comment by deepak-srivastava** [comment]
Thanks @pradpnayak. Is part of v2.0.1.
