### ISSUE TITLE
Contacts in Mailchimp are unsubscribed even though contacts are present in CiviCRM

### ISSUE THREAD

**Issue by pradpnayak** [veda-consulting/uk.co.vedaconsulting.mailchimp#277]
Our system has contacts that share same email address. Some contacts are not in a particular group but the code retrieves contact id for contact not in group and unsubcribes it from mail chimp group during push.

**Comment by pradpnayak** [comment]
Code cleanup and fixed at https://github.com/veda-consulting/uk.co.vedaconsulting.mailchimp/pull/275

**Comment by deepak-srivastava** [comment]
Thanks @pradpnayak. Fix is part of v2.0.1
