### ISSUE TITLE
Contacts Unsubscribed 

### ISSUE THREAD

**Issue by stevekessler** [veda-consulting/uk.co.vedaconsulting.mailchimp#278]
Hi, 

I hope I am not missing something simple. I have an issue where every time I sync an individual contact from CiviCRM to MailChimp it is set to unsubscribe.  

<img width="469" alt="screen shot 2017-05-29 at 2 05 27 pm" src="https://cloud.githubusercontent.com/assets/867985/26560986/f9d1a8d2-4477-11e7-84b7-82a5f316eb29.png">

The contact does not have any flags like "Do not email" or "NO BULK EMAILS" or "Deceased," on the CiviCRM side. 

To try and fix this I go into MailChimp and subscribe the user to the newsletter group.  I sync from MailChimp to CiviCRM.  Then I sync from CiviCRM to MailChimp and the contact is unsubscribed again like above.  

I am having this happen with about 5 contacts on this CiviCRM instance I am currently working on.  

Any help with this is gratefully appreciated.  

Thanks,
Steve

**Comment by notnotnate** [comment]
@stevekessler Did you get anywhere with this? 

I am experiencing a similar issue:

All new subscriptions synced via webhook are changed to unsubscribed in mailchimp (same message as above)  within about 10 minutes. This happens for both embed form subscriptions and 'generic-api' subscriptions.

**Comment by stevekessler** [comment]
@notnotnate I did not find a solution.  

What I did was I downloaded a full export from both Civi and MailChimp and I compared them with Access (you could use any DB tool).  This told me the exact research each person was having an issue.  

Hope this helps.  

-Steve

**Comment by notnotnate** [comment]
@stevekessler, i'm assuming you mean 'reason' not 'research'? 

If so, what reasons did you find for the issues? If not, can you elaborate on 'research'

**Comment by deepak-srivastava** [comment]
Please check latest release - v2.0.1. Multiple contacts with same email is the suspect. Relevant PR - https://github.com/veda-consulting/uk.co.vedaconsulting.mailchimp/pull/275
