### ISSUE TITLE
API Callback trouble

### ISSUE THREAD

**Issue by henniganmedia** [veda-consulting/uk.co.vedaconsulting.mailchimp#280]
Hey folks,

I'm running into an issue that I'm unsure is code-related or workflow-related, so I'm cross-posting on the CiviCRM StackExchange as well. I'm able to configure everything to talk well with MailChimp, but when I do a dry run Pull sync from MailChimp to a fresh CiviCRM group, I'm only seeing 10 Contacts syncing over from lists I know have between 13 and 700 Contacts. I've combed through the issue discussions but don't see any tracking of this particular issue. Is there an API issue I'm running into? I've tried a configuration both with a mature and a fresh MailChimp account. Thanks!

**Comment by henniganmedia** [comment]
Obviously, if this is workflow-related, I'm 100% great to close or delete. Thanks.

**Comment by henniganmedia** [comment]
Success, at least with a patchwork modification. 

I modified the /Sync.php file to add the appropriate API v.3.0 count call manually to the list membership URL on line 126. I'm not too familiar with PHP, but it looks like the 'count' => $batch_size, on line 127 isn't reporting properly to the API, or the API 3.0 change has updated how the count call works (appending it to the API call URL instead of the method used in 2.0.)

I'm a newbie to PHP development and implementation, so I don't have any recommended universal changes to this functionality in /Sync.php -- just wanted to report back a successful patch on a medium-sized list in Dry Run (~700 list members.)

I'll be doing more thorough "pull" and "push" sync testing tomorrow in a live environment so will report any errors or challenges with this temporary fix in my situation. Earlier tests didn't suggest a similar challenge with "push" sync so with luck that part of the equation is still functioning as intended.

**Comment by veda-consulting** [comment]
@henniganmedia was this all ok? Closing on the assumption it was.
