### ISSUE TITLE
Improve webhook security

### ISSUE THREAD

**Issue by michaelmcandrew** [veda-consulting/uk.co.vedaconsulting.mailchimp#282]
A couple of ways that we can improve the usability and security of the mailchimp webhook part of this extension:

* remove the webhook permission
* require and automatically generate a random secret key on the CiviCRM side for the webhook (users shouldn't have to make up a long unguessable string)

I'm interested to hear thoughts on this.

**Comment by deepak-srivastava** [comment]
See #292 (v2.0.1). Secret key is now auto generated. Permission not removed, but user is informed about it's state.

**Comment by veda-consulting** [comment]
Closing
