### ISSUE TITLE
Short array syntax incompatible with older PHP versions

### ISSUE THREAD

**Issue by xurizaemon** [veda-consulting/uk.co.vedaconsulting.mailchimp#285]
I will be advising the client to upgrade, but I figured I should report this here also.

Client is on PHP 5.3.3 which is ancient, but also listed as compatible with CiviCRM.

This extension uses short array syntax (eg [here](https://github.com/veda-consulting/uk.co.vedaconsulting.mailchimp/blob/master/mailchimp.php#L318)) which means the extension has its own PHP requirements that are higher than CiviCRM's.

Options might be:

* Add a status check to the extension to warn site owners. (The symptom here was that cron started failing; the extension seems to install OK - which is weird ... maybe they use a different PHP via HTTP to CLI ... but you're not going to pick *taht* up in a status check over HTTP ... ok nvm)
* Document the problem
* Ignore, since PHP5.3 is ancient anyway 😱😏
* Something else?

**Comment by veda-consulting** [comment]
@xurizaemon at the moment we're ignoring - as you might have guessed from the lack of response! We're testing against PHP7 and PHP5.6 at our end. I think 5.3 is well past its sell by date.
