### ISSUE TITLE
Sync two contacts with same email fails

### ISSUE THREAD

**Issue by adam-devapp** [veda-consulting/uk.co.vedaconsulting.mailchimp#287]
When syncing two contacts with the same email, the Sync fails for second person with a titanic error. 

(This isn't the same as the bug for a single contact with multiple emails.)

**Comment by adam-devapp** [comment]
https://github.com/veda-consulting/uk.co.vedaconsulting.mailchimp/commit/7243e7c92f53d9ddd844fa7af60a61d49f05bda8

**Comment by veda-consulting** [comment]
@adam-devapp I think this PR has been accepted into the extension, closing. Let me know if it hasn't.
