### ISSUE TITLE
"Manage Groups" table column count incorrect via AJAX

### ISSUE THREAD

**Issue by hoegrammer** [veda-consulting/uk.co.vedaconsulting.mailchimp#288]
When you first load the groups list (Groups->Manage Groups) the columns returned include a "Mailchimp Sync" column (empty on our system,but that might be down to configuration). However when you go to other pages or use the filter, the data is refreshed via AJAX. At this point the Mailchimp Sync column is not returned, but it still exists in the table, so all the data is moved one column to the left, and the "Contacts" and "Settings" links are broken.

**Comment by it-foraus** [comment]
We encountered the same problem. We use CiviCRM 4.7.23., on drupal 7.56. 
![image](https://user-images.githubusercontent.com/31011410/29568267-1b73aa6a-8750-11e7-8f10-f2f4420f57a7.png)
![image 1](https://user-images.githubusercontent.com/31011410/29568272-20c0bee0-8750-11e7-9a18-89b02dfa31ad.png)

**Comment by it-foraus** [comment]
#262

**Comment by deepak-srivastava** [comment]
Fixed with https://github.com/veda-consulting/uk.co.vedaconsulting.mailchimp/pull/286 (thanks to @kurund). Part of release v2.0.1.
