### ISSUE TITLE
Inconsistencies Between MailChimp and CiviCRM

### ISSUE THREAD

**Issue by stevekessler** [veda-consulting/uk.co.vedaconsulting.mailchimp#289]
Hi All,  

I am working on better understanding inconsistencies in the sync.  The most obvious example is we have people in CiviCRM that are not marked unsubscribed (Opt-Out) and yet in MailChimp they are.  

Any thoughts on how to ensure and audit integrity between the sources are much appreciated.  

Thanks,
Steve

**Comment by deepak-srivastava** [comment]
Please check latest release - v2.0.1. Multiple contacts with same email is the suspect. Relevant PR - #275
