### ISSUE TITLE
Contacts in mailchimp missing first name, last name, civiID

### ISSUE THREAD

**Issue by sunnycs121** [veda-consulting/uk.co.vedaconsulting.mailchimp#299]
After scheduled job ran to push contacts to mailchimp form civicrm, some contacts were missing important data like first name, last name, etc. I looked into the scheduled job log and for some contacts the sync failed with following error message:

Finished execution of Mailchimp Push Sync with result: Failure, Error message: Mailchimp API said: akamai_503

Screenshot attached.
![screenshot_14](https://user-images.githubusercontent.com/2493730/33906983-9ab70656-df51-11e7-8308-1cc232720750.png)

**Comment by veda-consulting** [comment]
@sunnycs121 Thank you for sharing all the details. Akamai is the firewall used by MailChimp. The error indicates your server IP is blocked. The only way to resolve this would be to move your website to another server with different IP address. If you are on a shared hosting, then even if one user hosted on the same server abuses MailChimp systems, then the server IP is blocked. Sometimes this resolves automatically within few days, but if it does not, changing your website to another server with different IP address is the only solution.
