### ISSUE TITLE
Extension permissions error

### ISSUE THREAD

**Issue by magnolia61** [veda-consulting/uk.co.vedaconsulting.mailchimp#78]
Using civicrm 4.4.6 and Joomla 3.3.3 I get the following permission error. I know this Joomla version is not fully supported by many civicrm extensions but I thought it would be good to let you know about this error. Maybe it's a quick fix :)

![civicrm_mailchimp_permission](https://cloud.githubusercontent.com/assets/2195908/3810959/e8d458b4-1c97-11e4-9579-1a63c6578cc9.png)

**Comment by stratosp** [comment]
I also have this problem with Joomla 3.3.3 and 3.3.6, with CiviCRM 4.4.11 on both sites I run.

I think this is not allowing me to carry out Basic Use, Step 3. "Make sure webhook url is accessible to public. If not, just make sure anonymous / public user has “allow webhook posts” permission."

Can't seem to find this option "allow webhook posts" in Joomla CiviCRM Permissions. Not exactly sure where this is meant to be enabled.

**Comment by veda-consulting** [comment]
@stratosp @magnolia61 I'm not sure what CiviCRM normally does about Joomla permissions, we'll have to take a look and see.

**Comment by vajeevan** [comment]
This issue has been fixed in mailchimp extension Version 1.8. Please have a look.

**Comment by stratosp** [comment]
Awesome, thanks for that. I'll take a look when I get a chance.

Regards,

Stratos

Stratos Patsikatheodorou

Mob: +61 401 295 179

**Comment by veda-consulting** [comment]
@stratosp closing, please re-open if its not fixed for you.
